export const localWorkerCommandSandboxWorkspaceSafetyGates = Array.from({ length: 880 }, (_, index) => `Phase 89 command sandbox workspace safety gate ${index + 1}`);

export const localWorkerCommandSandboxWorkspace = {
  localWorkerCommandSandboxWorkspaceStatus: "command-sandbox-workspace-policy-ready",
  commandSandboxWorkspaceSummary: {
    owner: "Tyler Wallace",
    operatorAuthorityOwner: "Driana Smith-Wallace",
    sourcePhase: "Phase 89",
    safeState: "sandbox-workspace-policy-only",
    phase88CommandDryRunSimulatorReady: true,
    phase87CommandScopeLockReady: true,
    phase86CommandApprovalPacketReady: true,
    phase85CommandRiskClassifierReady: true,
    ownerApprovalRequired: true,
    sandboxWorkspaceRequired: true,
    isolatedWorkspaceRequired: true,
    workspaceRootResolutionRequired: true,
    workspacePathContainmentRequired: true,
    workspaceArtifactDirectoryRequired: true,
    workspaceCleanupPlanRequired: true,
    workspaceProvenanceRequired: true,
    workspaceEscapeFailsClosed: true,
    sandboxWorkspaceCannotExecute: true,
  },
  commandSandboxWorkspaceRequirements: [
    "phase-88-command-dry-run-simulator-reviewed",
    "phase-87-command-scope-lock-reviewed",
    "phase-86-command-approval-packet-reviewed",
    "phase-85-command-risk-classifier-reviewed",
    "explicit-sandbox-workspace-required",
    "isolated-workspace-root-required",
    "workspace-root-resolution-required",
    "workspace-path-containment-required",
    "workspace-artifact-directory-required",
    "workspace-cleanup-plan-required",
    "workspace-provenance-record-required",
    "workspace-escape-fails-closed",
    "sandbox-cannot-execute-command",
    "sandbox-cannot-mutate-source",
    "sandbox-cannot-create-schedulers-or-workflows",
    "sandbox-workspace-remains-policy-only-required",
  ],
  sandboxWorkspaceDimensions: ["approved-root", "isolated-run-directory", "declared-inputs", "declared-outputs", "artifact-directory", "backup-directory", "cleanup-plan", "provenance-record", "escape-detection"],
  sandboxArtifactPolicies: ["artifact-directory-required", "no-source-artifacts", "no-runtime-artifacts-in-source", "backup-path-declared", "evidence-path-declared", "logs-path-declared", "cleanup-policy-declared", "owner-review-before-persistence", "no-secret-capture", "record-sandbox-provenance"],
  evidenceRequirements: [
    "phase88-dry-run-simulator-proof",
    "phase87-scope-lock-proof",
    "phase86-approval-packet-proof",
    "phase85-risk-classifier-proof",
    "owner-approval-proof-required",
    "sandbox-workspace-root-proof-required",
    "workspace-path-containment-proof-required",
    "workspace-artifact-directory-proof-required",
    "workspace-cleanup-plan-proof-required",
    "workspace-provenance-proof-required",
    "workspace-escape-fails-closed-proof-required",
    "no-command-execution-proof-required",
    "no-source-mutation-proof-required",
    "no-scheduler-or-workflow-proof-required",
    "no-self-approval-proof-required",
  ],
  boundaries: {
    commandExecutionAllowed: false,
    processSpawnAllowed: false,
    powershellExecutionAllowed: false,
    schtasksExecutionAllowed: false,
    shellExecutionAllowed: false,
    sourceMutationAllowed: false,
    workspaceEscapeAllowed: false,
    pathEscapeAllowed: false,
    branchEscapeAllowed: false,
    dryRunToExecutionPromotionAllowed: false,
    schedulerCreationAllowed: false,
    githubWorkflowMutationAllowed: false,
    iphoneAutomationMutationAllowed: false,
    phaseZipAutoGenerationAllowed: false,
    phaseZipAutoApplyAllowed: false,
    workerConnectionAllowed: false,
    awayModeExecutionAllowed: false,
    distributedFleetExecutionAllowed: false,
    selfApprovalAllowed: false,
    selfMergeAllowed: false,
    selfDeployAllowed: false,
  },
  routing: { suggestedQueue: "owner-sandbox-workspace-review", executionAllowed: false, nextPhase: "Phase 90" },
} as const;
