export const phaseTroubleshootingLoop = {
  phaseTroubleshootingStatus: "phase-troubleshooting-loop-ready",
  phase: "100F",
  title: "Phase Troubleshooting Loop v1",
  owner: "Tyler Wallace",
  operatorAuthorityOwner: "Driana Smith-Wallace",
  sourceApplyQueueId: "phase100e-demo-phase-apply-queue",
  declaredFileCount: 5,
  phaseTroubleshootingRequirementCount: 34,
  phaseTroubleshootingFieldCount: 60,
  phaseFactoryStageCount: 8,
  troubleshootingCaseCount: 8,
  roadmapTrackCount: 13,
  multiLanguageProductionTargetCount: 18,
  safetyGateCount: 1680,
  phaseTroubleshootingAllowed: true,
  phaseApplyQueueReadAllowed: true,
  diagnosticEvidencePacketAllowed: true,
  repairGuidanceAllowed: true,
  autoFixAllowed: false,
  applyExecutionAllowed: false,
  patchExecutionAllowed: false,
  projectRepoSourceMutationAllowed: false,
  realProjectBranchCreationAllowed: false,
  realProjectMergeExecutionAllowed: false,
  gitPushAllowed: false,
  tagCreationAllowed: false,
  arbitraryCommandAllowed: false,
  shellExecutionAllowed: false,
  schedulerWorkflowMutationAllowed: false,
  iPhoneAutomationMutationAllowed: false,
  fleetExecutionAllowed: false,
  awayModeExecutionAllowed: false,
  selfApprovalAllowed: false,
  selfMergeAllowed: false,
  selfDeployAllowed: false,
  productionDeploymentAllowed: false,
} as const;

export const phaseTroubleshootingLoopSafetyGates = [
  { label: "Phase 100F autofix", value: "blocked", tone: "safe" as const },
  { label: "Phase 100F apply execution", value: "blocked", tone: "safe" as const },
  { label: "Phase 100F patch execution", value: "blocked", tone: "safe" as const },
  { label: "Phase 100F source mutation", value: "blocked", tone: "safe" as const },
  { label: "Phase 100F real branch/merge", value: "blocked", tone: "safe" as const },
  { label: "Phase 100F git push/tag", value: "blocked", tone: "safe" as const },
  { label: "Phase 100F shell/scheduler/fleet", value: "blocked", tone: "safe" as const },
  { label: "Phase 100F self-governance", value: "blocked", tone: "safe" as const },
];
