export const phaseSpecGenerator = {
  phaseSpecGeneratorStatus: "phase-spec-generator-ready",
  sourcePhase: "Phase 100B — Phase Spec Generator v1",
  safeState: "phase-factory-spec-generation-only",
  owner: "Tyler Wallace",
  operatorAuthorityOwner: "Driana Smith-Wallace",
  sourceBacklogId: "phase100a-demo-phase-backlog",
  phaseFactoryStageCount: 8,
  phaseSpecCount: 8,
  roadmapTrackCount: 13,
  multiLanguageProductionTargetCount: 18,
  safetyGateCount: 1440,
  phaseSpecGenerationAllowed: true,
  phaseBacklogPacketReadAllowed: true,
  ownerReviewSpecPacketAllowed: true,
  overlayZipBuildAllowed: false,
  patchExecutionAllowed: false,
  projectRepoSourceMutationAllowed: false,
  realProjectBranchCreationAllowed: false,
  realProjectMergeExecutionAllowed: false,
  gitPushAllowed: false,
  tagCreationAllowed: false,
  arbitraryCommandAllowed: false,
  shellExecutionAllowed: false,
  selfApprovalAllowed: false,
  selfMergeAllowed: false,
  selfDeployAllowed: false,
};

export const phaseSpecGeneratorSafetyGates = [
  "Phase 100A phase backlog generator ready",
  "Phase 100B reads backlog lineage and produces owner-reviewable specs only",
  "Each phase spec must include purpose, scope, safety boundaries, evidence, validation, rollback, and owner review",
  "Phase specs must remain exact, ordered, and roadmap-scoped from 100A through 100H",
  "Multi-language production doctrine remains preserved",
  "Overlay ZIP building remains blocked until Phase 100C",
  "Patch execution remains blocked",
  "Project repo source mutation blocked",
  "Real local and remote Git branch creation blocked",
  "Real project merge execution blocked",
  "Git push and tag creation blocked",
  "Arbitrary command and shell execution blocked",
  "Scheduler, workflow, iPhone automation, fleet, and away-mode execution blocked",
  "Self-approval, self-merge, and self-deploy blocked",
];
