export const phaseFactoryAlpha = {
  phaseFactoryAlphaStatus: "phase-factory-alpha-ready",
  phase: "100H",
  title: "Phase Factory Alpha v1",
  owner: "Tyler Wallace",
  operatorAuthorityOwner: "Driana Smith-Wallace",
  sourceEvidencePackId: "phase100g-demo-phase-evidence-pack",
  declaredFileCount: 5,
  phaseFactoryAlphaRequirementCount: 38,
  phaseFactoryAlphaFieldCount: 74,
  phaseFactoryStageCount: 8,
  phaseFactoryIntegrationCount: 8,
  roadmapTrackCount: 13,
  multiLanguageProductionTargetCount: 18,
  safetyGateCount: 1800,
  phaseFactoryAlphaAllowed: true,
  phaseBacklogReadAllowed: true,
  phaseSpecReadAllowed: true,
  phaseOverlayManifestReadAllowed: true,
  phaseZipValidationReadAllowed: true,
  phaseApplyQueueReadAllowed: true,
  phaseTroubleshootingReadAllowed: true,
  phaseEvidencePackReadAllowed: true,
  ownerReviewAlphaPacketAllowed: true,
  autoRunFuturePhasesAllowed: false,
  autoFixAllowed: false,
  applyExecutionAllowed: false,
  patchExecutionAllowed: false,
  projectRepoSourceMutationAllowed: false,
  realProjectBranchCreationAllowed: false,
  realProjectMergeExecutionAllowed: false,
  gitPushAllowed: false,
  tagCreationAllowed: false,
  arbitraryCommandAllowed: false,
  shellExecutionAllowed: false,
  schedulerWorkflowMutationAllowed: false,
  iPhoneAutomationMutationAllowed: false,
  fleetExecutionAllowed: false,
  awayModeExecutionAllowed: false,
  selfApprovalAllowed: false,
  selfMergeAllowed: false,
  selfDeployAllowed: false,
  productionDeploymentAllowed: false,
} as const;

export const phaseFactoryAlphaSafetyGates = [
  { label: "Phase 100H future phase auto-run", value: "blocked", tone: "safe" as const },
  { label: "Phase 100H autofix", value: "blocked", tone: "safe" as const },
  { label: "Phase 100H apply execution", value: "blocked", tone: "safe" as const },
  { label: "Phase 100H patch execution", value: "blocked", tone: "safe" as const },
  { label: "Phase 100H source mutation", value: "blocked", tone: "safe" as const },
  { label: "Phase 100H real branch/merge", value: "blocked", tone: "safe" as const },
  { label: "Phase 100H git push/tag", value: "blocked", tone: "safe" as const },
  { label: "Phase 100H shell/scheduler/fleet/self", value: "blocked", tone: "safe" as const },
];
