export const phaseZipValidator = {
  phaseZipValidatorStatus: "phase-zip-validator-ready",
  phase: "100D",
  title: "Phase ZIP Validator v1",
  owner: "Tyler Wallace",
  operatorAuthorityOwner: "Driana Smith-Wallace",
  sourceOverlayZipId: "phase100c-demo-phase-overlay-zip",
  declaredFileCount: 5,
  phaseZipValidatorRequirementCount: 30,
  phaseZipValidatorFieldCount: 50,
  phaseFactoryStageCount: 8,
  phaseZipValidationPackageCount: 8,
  roadmapTrackCount: 13,
  multiLanguageProductionTargetCount: 18,
  safetyGateCount: 1560,
  phaseZipValidationAllowed: true,
  phaseOverlayPackageManifestReadAllowed: true,
  validationEvidencePacketAllowed: true,
  checksumManifestAllowed: true,
  overlayZipBuildAllowed: false,
  patchExecutionAllowed: false,
  projectRepoSourceMutationAllowed: false,
  realProjectBranchCreationAllowed: false,
  realProjectMergeExecutionAllowed: false,
  gitPushAllowed: false,
  tagCreationAllowed: false,
  arbitraryCommandAllowed: false,
  shellExecutionAllowed: false,
  selfApprovalAllowed: false,
  selfMergeAllowed: false,
  selfDeployAllowed: false,
  productionDeploymentAllowed: false,
} as const;

export const phaseZipValidatorSafetyGates = [
  { label: "Phase 100D overlay ZIP build", value: "blocked", tone: "safe" as const },
  { label: "Phase 100D patch execution", value: "blocked", tone: "safe" as const },
  { label: "Phase 100D source mutation", value: "blocked", tone: "safe" as const },
  { label: "Phase 100D real branch/merge", value: "blocked", tone: "safe" as const },
  { label: "Phase 100D git push/tag", value: "blocked", tone: "safe" as const },
  { label: "Phase 100D shell execution", value: "blocked", tone: "safe" as const },
  { label: "Phase 100D self-governance", value: "blocked", tone: "safe" as const },
];
