export const phaseOverlayZipBuilder = {
  phaseOverlayZipBuilderStatus: "phase-overlay-zip-builder-ready",
  phase: "100C",
  title: "Phase Overlay ZIP Builder v1",
  owner: "Tyler Wallace",
  operatorAuthorityOwner: "Driana Smith-Wallace",
  sourceSpecId: "phase100b-demo-phase-spec",
  declaredFileCount: 5,
  phaseOverlayZipRequirementCount: 28,
  phaseOverlayZipFieldCount: 46,
  phaseFactoryStageCount: 8,
  phaseOverlayPackageCount: 8,
  roadmapTrackCount: 13,
  multiLanguageProductionTargetCount: 18,
  safetyGateCount: 1500,
  phaseOverlayZipBuildAllowed: true,
  phaseSpecPacketReadAllowed: true,
  ownerReviewOverlayPackageAllowed: true,
  overlayPackageManifestAllowed: true,
  patchExecutionAllowed: false,
  projectRepoSourceMutationAllowed: false,
  realProjectBranchCreationAllowed: false,
  realProjectMergeExecutionAllowed: false,
  gitPushAllowed: false,
  tagCreationAllowed: false,
  arbitraryCommandAllowed: false,
  shellExecutionAllowed: false,
  selfApprovalAllowed: false,
  selfMergeAllowed: false,
  selfDeployAllowed: false,
  productionDeploymentAllowed: false,
} as const;

export const phaseOverlayZipBuilderSafetyGates = [
  { label: "Phase 100C patch execution", value: "blocked", tone: "safe" as const },
  { label: "Phase 100C source mutation", value: "blocked", tone: "safe" as const },
  { label: "Phase 100C real branch creation", value: "blocked", tone: "safe" as const },
  { label: "Phase 100C real merge execution", value: "blocked", tone: "safe" as const },
  { label: "Phase 100C git push/tag", value: "blocked", tone: "safe" as const },
  { label: "Phase 100C shell execution", value: "blocked", tone: "safe" as const },
  { label: "Phase 100C self-governance", value: "blocked", tone: "safe" as const },
];
