export const phaseEvidencePack = {
  phaseEvidencePackStatus: "phase-evidence-pack-ready",
  phase: "100G",
  title: "Phase Evidence Pack v1",
  owner: "Tyler Wallace",
  operatorAuthorityOwner: "Driana Smith-Wallace",
  sourceTroubleshootingId: "phase100f-demo-phase-troubleshooting-loop",
  declaredFileCount: 5,
  phaseEvidencePackRequirementCount: 36,
  phaseEvidencePackFieldCount: 66,
  phaseFactoryStageCount: 8,
  phaseEvidencePackItemCount: 8,
  roadmapTrackCount: 13,
  multiLanguageProductionTargetCount: 18,
  safetyGateCount: 1740,
  phaseEvidencePackAllowed: true,
  phaseTroubleshootingEvidenceReadAllowed: true,
  phaseEvidenceBundleAllowed: true,
  ownerReviewEvidencePackAllowed: true,
  autoFixAllowed: false,
  applyExecutionAllowed: false,
  patchExecutionAllowed: false,
  projectRepoSourceMutationAllowed: false,
  realProjectBranchCreationAllowed: false,
  realProjectMergeExecutionAllowed: false,
  gitPushAllowed: false,
  tagCreationAllowed: false,
  arbitraryCommandAllowed: false,
  shellExecutionAllowed: false,
  schedulerWorkflowMutationAllowed: false,
  iPhoneAutomationMutationAllowed: false,
  fleetExecutionAllowed: false,
  awayModeExecutionAllowed: false,
  selfApprovalAllowed: false,
  selfMergeAllowed: false,
  selfDeployAllowed: false,
  productionDeploymentAllowed: false,
} as const;

export const phaseEvidencePackSafetyGates = [
  { label: "Phase 100G autofix", value: "blocked", tone: "safe" as const },
  { label: "Phase 100G apply execution", value: "blocked", tone: "safe" as const },
  { label: "Phase 100G patch execution", value: "blocked", tone: "safe" as const },
  { label: "Phase 100G source mutation", value: "blocked", tone: "safe" as const },
  { label: "Phase 100G real branch/merge", value: "blocked", tone: "safe" as const },
  { label: "Phase 100G git push/tag", value: "blocked", tone: "safe" as const },
  { label: "Phase 100G shell/scheduler/fleet", value: "blocked", tone: "safe" as const },
  { label: "Phase 100G self-governance", value: "blocked", tone: "safe" as const },
];
