export const phaseApplyQueue = {
  phaseApplyQueueStatus: "phase-apply-queue-ready",
  phase: "100E",
  title: "Phase Apply Queue v1",
  owner: "Tyler Wallace",
  operatorAuthorityOwner: "Driana Smith-Wallace",
  sourceZipValidatorId: "phase100d-demo-phase-zip-validator",
  declaredFileCount: 5,
  phaseApplyQueueRequirementCount: 32,
  phaseApplyQueueFieldCount: 55,
  phaseFactoryStageCount: 8,
  phaseApplyQueueItemCount: 8,
  roadmapTrackCount: 13,
  multiLanguageProductionTargetCount: 18,
  safetyGateCount: 1620,
  phaseApplyQueueAllowed: true,
  phaseZipValidationEvidenceReadAllowed: true,
  ownerReviewQueuePacketAllowed: true,
  manualApplyReviewAllowed: true,
  applyExecutionAllowed: false,
  patchExecutionAllowed: false,
  projectRepoSourceMutationAllowed: false,
  realProjectBranchCreationAllowed: false,
  realProjectMergeExecutionAllowed: false,
  gitPushAllowed: false,
  tagCreationAllowed: false,
  arbitraryCommandAllowed: false,
  shellExecutionAllowed: false,
  schedulerWorkflowMutationAllowed: false,
  iPhoneAutomationMutationAllowed: false,
  fleetExecutionAllowed: false,
  awayModeExecutionAllowed: false,
  selfApprovalAllowed: false,
  selfMergeAllowed: false,
  selfDeployAllowed: false,
  productionDeploymentAllowed: false,
} as const;

export const phaseApplyQueueSafetyGates = [
  { label: "Phase 100E apply execution", value: "blocked", tone: "safe" as const },
  { label: "Phase 100E patch execution", value: "blocked", tone: "safe" as const },
  { label: "Phase 100E source mutation", value: "blocked", tone: "safe" as const },
  { label: "Phase 100E real branch/merge", value: "blocked", tone: "safe" as const },
  { label: "Phase 100E git push/tag", value: "blocked", tone: "safe" as const },
  { label: "Phase 100E shell/scheduler/fleet", value: "blocked", tone: "safe" as const },
  { label: "Phase 100E self-governance", value: "blocked", tone: "safe" as const },
];
