export const workerActivationReviewQueue = {
  workerActivationReviewQueueStatus: "worker-activation-review-queue-ready",
  phase: "103",
  title: "Worker Activation Review Queue v1",
  owner: "Tyler Wallace",
  operatorAuthorityOwner: "Driana Smith-Wallace",
  sourceWorkerCapabilityCardsId: "phase102-demo-worker-capability-cards",
  declaredFileCount: 5,
  workerActivationReviewQueueRequirementCount: 44,
  workerActivationReviewQueueFieldCount: 90,
  activationQueueItemCount: 12,
  decisionTemplateCount: 12,
  readinessChecklistCount: 12,
  roadmapTrackCount: 13,
  multiLanguageProductionTargetCount: 18,
  safetyGateCount: 1980,
  workerActivationReviewQueueAllowed: true,
  workerCapabilityCardsReadAllowed: true,
  activationQueueManifestAllowed: true,
  ownerReviewActivationPacketAllowed: true,
  activationDecisionDraftAllowed: true,
  workerActivationAllowed: false,
  workerExecutionAllowed: false,
  workerSpawningAllowed: false,
  autonomousDelegationAllowed: false,
  schedulerWorkflowMutationAllowed: false,
  iPhoneAutomationMutationAllowed: false,
  awayModeExecutionAllowed: false,
  fleetExecutionAllowed: false,
  applyExecutionAllowed: false,
  patchExecutionAllowed: false,
  projectRepoSourceMutationAllowed: false,
  realProjectBranchCreationAllowed: false,
  realProjectMergeExecutionAllowed: false,
  gitPushAllowed: false,
  tagCreationAllowed: false,
  arbitraryCommandAllowed: false,
  shellExecutionAllowed: false,
  selfApprovalAllowed: false,
  selfMergeAllowed: false,
  selfDeployAllowed: false,
  productionDeploymentAllowed: false,
} as const;

export const workerActivationReviewQueueSafetyGates = [
  { label: "Phase 103 worker activation", value: "blocked", tone: "safe" as const },
  { label: "Phase 103 worker execution", value: "blocked", tone: "safe" as const },
  { label: "Phase 103 worker spawning", value: "blocked", tone: "safe" as const },
  { label: "Phase 103 autonomous delegation", value: "blocked", tone: "safe" as const },
  { label: "Phase 103 scheduler/iPhone mutation", value: "blocked", tone: "safe" as const },
  { label: "Phase 103 apply/patch/source mutation", value: "blocked", tone: "safe" as const },
  { label: "Phase 103 real branch/merge", value: "blocked", tone: "safe" as const },
  { label: "Phase 103 Git/shell/fleet/self/deploy", value: "blocked", tone: "safe" as const },
];
