export const workerCapabilityCards = {
  workerCapabilityCardsStatus: "worker-capability-cards-ready",
  phase: "102",
  title: "Worker Capability Cards v1",
  owner: "Tyler Wallace",
  operatorAuthorityOwner: "Driana Smith-Wallace",
  sourceWorkerFleetRegistryId: "phase101-demo-worker-fleet-registry",
  declaredFileCount: 5,
  workerCapabilityCardsRequirementCount: 42,
  workerCapabilityCardsFieldCount: 84,
  workerCapabilityCardCount: 12,
  inputContractCount: 12,
  outputContractCount: 12,
  roadmapTrackCount: 13,
  multiLanguageProductionTargetCount: 18,
  safetyGateCount: 1920,
  workerCapabilityCardsAllowed: true,
  workerFleetRegistryReadAllowed: true,
  capabilityCardCatalogAllowed: true,
  inputOutputContractAllowed: true,
  ownerReviewCapabilityPacketAllowed: true,
  workerExecutionAllowed: false,
  workerSpawningAllowed: false,
  autonomousDelegationAllowed: false,
  schedulerWorkflowMutationAllowed: false,
  iPhoneAutomationMutationAllowed: false,
  awayModeExecutionAllowed: false,
  fleetExecutionAllowed: false,
  applyExecutionAllowed: false,
  patchExecutionAllowed: false,
  projectRepoSourceMutationAllowed: false,
  realProjectBranchCreationAllowed: false,
  realProjectMergeExecutionAllowed: false,
  gitPushAllowed: false,
  tagCreationAllowed: false,
  arbitraryCommandAllowed: false,
  shellExecutionAllowed: false,
  selfApprovalAllowed: false,
  selfMergeAllowed: false,
  selfDeployAllowed: false,
  productionDeploymentAllowed: false,
} as const;

export const workerCapabilityCardsSafetyGates = [
  { label: "Phase 102 worker execution", value: "blocked", tone: "safe" as const },
  { label: "Phase 102 worker spawning", value: "blocked", tone: "safe" as const },
  { label: "Phase 102 autonomous delegation", value: "blocked", tone: "safe" as const },
  { label: "Phase 102 scheduler/iPhone mutation", value: "blocked", tone: "safe" as const },
  { label: "Phase 102 apply/patch/source mutation", value: "blocked", tone: "safe" as const },
  { label: "Phase 102 real branch/merge", value: "blocked", tone: "safe" as const },
  { label: "Phase 102 Git push/tag", value: "blocked", tone: "safe" as const },
  { label: "Phase 102 shell/fleet/self/deploy", value: "blocked", tone: "safe" as const },
];
