export const workerActivationDecisionRecord = {
  workerActivationDecisionRecordStatus: "worker-activation-decision-record-ready",
  phase: "105",
  title: "Worker Activation Decision Record v1",
  owner: "Tyler Wallace",
  operatorAuthorityOwner: "Driana Smith-Wallace",
  sourceWorkerActivationGateId: "phase104-demo-worker-activation-gate",
  declaredFileCount: 5,
  workerActivationDecisionRecordRequirementCount: 48,
  workerActivationDecisionRecordFieldCount: 106,
  activationDecisionRecordCount: 12,
  ownerActivationDecisionRecordCount: 12,
  decisionAuditRecordCount: 12,
  activationDenialRecordCount: 12,
  roadmapTrackCount: 13,
  multiLanguageProductionTargetCount: 18,
  safetyGateCount: 2100,
  workerActivationDecisionRecordAllowed: true,
  workerActivationGateReadAllowed: true,
  activationDecisionRecordManifestAllowed: true,
  ownerReviewDecisionRecordPacketAllowed: true,
  ownerActivationDecisionDraftAllowed: true,
  activationDenialRecordAllowed: true,
  workerActivationAllowed: false,
  workerExecutionAllowed: false,
  workerSpawningAllowed: false,
  autonomousDelegationAllowed: false,
  schedulerWorkflowMutationAllowed: false,
  iPhoneAutomationMutationAllowed: false,
  awayModeExecutionAllowed: false,
  fleetExecutionAllowed: false,
  applyExecutionAllowed: false,
  patchExecutionAllowed: false,
  projectRepoSourceMutationAllowed: false,
  realProjectBranchCreationAllowed: false,
  realProjectMergeExecutionAllowed: false,
  gitPushAllowed: false,
  tagCreationAllowed: false,
  arbitraryCommandAllowed: false,
  shellExecutionAllowed: false,
  selfApprovalAllowed: false,
  selfMergeAllowed: false,
  selfDeployAllowed: false,
  productionDeploymentAllowed: false,
  activationTokenIssued: false,
} as const;

export const workerActivationDecisionRecordSafetyGates = [
  { label: "Phase 105 worker activation", value: "blocked", tone: "safe" as const },
  { label: "Phase 105 activation token", value: "blocked", tone: "safe" as const },
  { label: "Phase 105 worker execution", value: "blocked", tone: "safe" as const },
  { label: "Phase 105 worker spawning", value: "blocked", tone: "safe" as const },
  { label: "Phase 105 autonomous delegation", value: "blocked", tone: "safe" as const },
  { label: "Phase 105 scheduler/iPhone mutation", value: "blocked", tone: "safe" as const },
  { label: "Phase 105 apply/patch/source mutation", value: "blocked", tone: "safe" as const },
  { label: "Phase 105 Git/shell/fleet/self/deploy", value: "blocked", tone: "safe" as const },
];
