export const workerFleetRegistry = {
  workerFleetRegistryStatus: "worker-fleet-registry-ready",
  phase: "101",
  title: "Worker Fleet Registry v1",
  owner: "Tyler Wallace",
  operatorAuthorityOwner: "Driana Smith-Wallace",
  sourcePhaseFactoryAlphaId: "phase100h-demo-phase-factory-alpha",
  declaredFileCount: 5,
  workerFleetRegistryRequirementCount: 40,
  workerFleetRegistryFieldCount: 78,
  workerFleetLaneCount: 10,
  workerDefinitionCount: 12,
  roadmapTrackCount: 13,
  multiLanguageProductionTargetCount: 18,
  safetyGateCount: 1860,
  workerFleetRegistryAllowed: true,
  phaseFactoryAlphaReadAllowed: true,
  workerDefinitionCatalogAllowed: true,
  ownerReviewFleetPacketAllowed: true,
  workerExecutionAllowed: false,
  workerSpawningAllowed: false,
  autonomousDelegationAllowed: false,
  schedulerWorkflowMutationAllowed: false,
  iPhoneAutomationMutationAllowed: false,
  awayModeExecutionAllowed: false,
  fleetExecutionAllowed: false,
  applyExecutionAllowed: false,
  patchExecutionAllowed: false,
  projectRepoSourceMutationAllowed: false,
  realProjectBranchCreationAllowed: false,
  realProjectMergeExecutionAllowed: false,
  gitPushAllowed: false,
  tagCreationAllowed: false,
  arbitraryCommandAllowed: false,
  shellExecutionAllowed: false,
  selfApprovalAllowed: false,
  selfMergeAllowed: false,
  selfDeployAllowed: false,
  productionDeploymentAllowed: false,
} as const;

export const workerFleetRegistrySafetyGates = [
  { label: "Phase 101 worker execution", value: "blocked", tone: "safe" as const },
  { label: "Phase 101 worker spawning", value: "blocked", tone: "safe" as const },
  { label: "Phase 101 autonomous delegation", value: "blocked", tone: "safe" as const },
  { label: "Phase 101 scheduler/iPhone mutation", value: "blocked", tone: "safe" as const },
  { label: "Phase 101 apply/patch/source mutation", value: "blocked", tone: "safe" as const },
  { label: "Phase 101 real branch/merge", value: "blocked", tone: "safe" as const },
  { label: "Phase 101 Git push/tag", value: "blocked", tone: "safe" as const },
  { label: "Phase 101 shell/fleet/self/deploy", value: "blocked", tone: "safe" as const },
];
