export const workerActivationGate = {
  workerActivationGateStatus: "worker-activation-gate-ready",
  phase: "104",
  title: "Worker Activation Gate v1",
  owner: "Tyler Wallace",
  operatorAuthorityOwner: "Driana Smith-Wallace",
  sourceWorkerActivationReviewQueueId: "phase103-demo-worker-activation-review-queue",
  declaredFileCount: 5,
  workerActivationGateRequirementCount: 46,
  workerActivationGateFieldCount: 100,
  activationGateItemCount: 12,
  eligibilityReviewCount: 12,
  gateDecisionDraftCount: 12,
  readinessGateChecklistCount: 12,
  roadmapTrackCount: 13,
  multiLanguageProductionTargetCount: 18,
  safetyGateCount: 2040,
  workerActivationGateAllowed: true,
  workerActivationReviewQueueReadAllowed: true,
  activationGateManifestAllowed: true,
  ownerReviewActivationGatePacketAllowed: true,
  activationEligibilityReviewAllowed: true,
  activationGateDecisionDraftAllowed: true,
  workerActivationAllowed: false,
  workerExecutionAllowed: false,
  workerSpawningAllowed: false,
  autonomousDelegationAllowed: false,
  schedulerWorkflowMutationAllowed: false,
  iPhoneAutomationMutationAllowed: false,
  awayModeExecutionAllowed: false,
  fleetExecutionAllowed: false,
  applyExecutionAllowed: false,
  patchExecutionAllowed: false,
  projectRepoSourceMutationAllowed: false,
  realProjectBranchCreationAllowed: false,
  realProjectMergeExecutionAllowed: false,
  gitPushAllowed: false,
  tagCreationAllowed: false,
  arbitraryCommandAllowed: false,
  shellExecutionAllowed: false,
  selfApprovalAllowed: false,
  selfMergeAllowed: false,
  selfDeployAllowed: false,
  productionDeploymentAllowed: false,
  activationTokenIssued: false,
} as const;

export const workerActivationGateSafetyGates = [
  { label: "Phase 104 worker activation", value: "blocked", tone: "safe" as const },
  { label: "Phase 104 activation token", value: "blocked", tone: "safe" as const },
  { label: "Phase 104 worker execution", value: "blocked", tone: "safe" as const },
  { label: "Phase 104 worker spawning", value: "blocked", tone: "safe" as const },
  { label: "Phase 104 autonomous delegation", value: "blocked", tone: "safe" as const },
  { label: "Phase 104 scheduler/iPhone mutation", value: "blocked", tone: "safe" as const },
  { label: "Phase 104 apply/patch/source mutation", value: "blocked", tone: "safe" as const },
  { label: "Phase 104 Git/shell/fleet/self/deploy", value: "blocked", tone: "safe" as const },
];
