import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { describe, expect, it } from "vitest";
import { EVIDENCE_MANIFEST_FILE, EVIDENCE_MANIFEST_SCHEMA, RESTRICTED_USER_NEGATIVE_CASES, RESTRICTED_USER_PROFILE_ID, RESTRICTED_USER_REASON_CODES, WINDOWS_TOOLS, manifestDigest, proveRestrictedUserEvidence, runWindowsCommand, sha256, verifyRestrictedUserEvidence } from "@sera/portable-base-mvp";

const hash = "a".repeat(64), sid = "S-1-5-21-1-2-3-1002", sessionId = "session-fixture", nonce = "b".repeat(64), collector = "c".repeat(64);
const visuals = ["packaged-launcher", "desktop-operator-loaded", "runtime-health", "supported-intake", "provenance", "model-candidate", "evaluation", "operator-review", "digest-bound-approval", "closeout", "evidence-history"];
const roles = ["repository-root", "repository-git", "repository-node-modules", "repository-sera", "development-sqlite", "development-codex", "sera-sandbox", "dev-root", "configured-private-root"];

function makeBundle(): string {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), "sera-observation-bundle-"));
  const governance: any = { status: "approved", approvedRole: "project-owner", approvedProfile: RESTRICTED_USER_PROFILE_ID, allowedClaims: ["RELEASE_INDEPENDENCE_PROVEN", "CERTIFIED_HOST_PROFILE_PROVEN"], prohibitedClaims: ["CROSS_HOST_PORTABILITY_PROVEN"] };
  write(root, "governance-decision.json", governance);
  const prep: any = { evidenceMode: "synthetic-test-v2", sessionId, nonce, hostProfileId: "host-1", developmentSid: "S-1-5-21-1-2-3-1001", repository: { canonicalPath: "C:\\dev\\repo" }, release: { zipSha256: hash, releaseManifestDigest: hash }, collectors: [{ sha256: collector }], governanceDecisionDigest: fileHash(root, "governance-decision.json") };
  write(root, "preparation-manifest.json", prep);
  write(root, "pre/account-token.json", { proofSid: sid, activeTokenSid: sid, elevationType: "limited", tokenElevated: false, enabledGroupSids: ["S-1-5-32-545"], accountSource: "Local", standardLocalAccount: true, profileSid: sid, profilePath: "C:\\Users\\proof", profileCreatedAt: "2026-07-21T00:00:00.000Z", collectorExecutable: "C:\\Windows\\System32\\whoami.exe", rawIdentitySha256: hash, rawGroupsSha256: hash, rawTokenSha256: hash, capturedAt: "2026-07-21T00:00:00.000Z" });
  write(root,"pre/collector-provenance.json",{invocation:"NON_PROMOTABLE_DEVELOPMENT_SMOKE",startedAt:"2026-07-21T00:00:00.000Z",sessionId,nonce,proofSid:sid});write(root,"pre/workflow-start.json",{workflowStartedAt:"2026-07-21T00:01:00.000Z",sessionId,nonce});write(root,"pre/workflow-complete.json",{workflowCompletedAt:"2026-07-21T00:59:00.000Z",sessionId,nonce});
  const operations=["identity","enumerate","known-child-read","file-open","execution","reparse-inspection","parent-traversal"];
  write(root, "pre/source-denial.json", { observations: roles.flatMap((targetRole) => operations.map(operation => ({ targetRole, operation, requestedPath: `C:\\dev\\${targetRole}`, normalizedPath: `C:\\dev\\${targetRole}`, classification: targetRole === "sera-sandbox" ? "ABSENT" : "EXISTS_ACCESS_DENIED", proofSid: sid, windowsErrorCode: targetRole === "sera-sandbox" ? 2 : 5, timestamp: "2026-07-21T00:00:00.000Z", parentTraversalBlocked: true }))) });
  write(root, "pre/release-runtime.json", { releaseRoot: "C:\\SERA Proof\\Release", releaseRootIsUnc: false, zipSha256: hash, releaseManifestDigest: hash, treeSha256: hash, runtimeExists: true, runtimeSha256: hash, observedExecutableSha256: hash, runtimeSize: 100, observedExecutableSize: 100, runtimePath: "C:\\SERA Proof\\Release\\runtime\\node.exe", observedExecutablePath: "C:\\SERA Proof\\Release\\runtime\\node.exe", execPath: "C:\\SERA Proof\\Release\\runtime\\node.exe", explicitReleaseRelativeLaunch: true, shellUsed: false, launcherKind: "packaged", pid: 100, parentPid: 99, processVersion: "v24", processArch: "x64", arguments: ["app.cjs"], sessionId, proofSid: sid, startedAt: "2026-07-21T00:00:00.000Z", releaseIdentity: "release-1" });
  write(root, "pre/process-events.json", { liveSubscription:true,sourceEventType:"Win32_ProcessStartTrace",readyHandshake: true, completeness: "COMPLETE", sessionId,nonce, proofSid: sid, startedAt: "2026-07-21T00:00:00.000Z", stoppedAt: "2026-07-21T01:00:00.000Z", events: [{ executableName: "node.exe", executablePath: "C:\\SERA Proof\\Release\\runtime\\node.exe", pid: 100, parentPid: 99, proofSid: sid, timestamp: "2026-07-21T00:00:01.000Z",sourceEventType:"Win32_ProcessStartTrace",enrichmentStatus:"OBSERVED_AND_ENRICHED" }] });
  write(root, "pre/environment.json", { pid: 100, sessionId, createdFromAllowlist: true, secretValueWritten: false, developmentPathPresent: false, coverage: ["PATH","PATHEXT","SystemRoot","WINDIR","TEMP","TMP","USERPROFILE","LOCALAPPDATA","APPDATA","NODE_PATH","NODE_OPTIONS","npm_config_*","NPM_CONFIG_*","GIT_*","CODEX_*","PROXY_*","CLOUD_CREDENTIALS","PROVIDER_CREDENTIALS","DEVELOPMENT_PATHS"], entries: [{ key: "PATH", classification: "digest-only", valueDigest: hash }, { key: "NODE_OPTIONS", classification: "absent" }] });
  writeBytes(root,"pre/ollama-request.bin",Buffer.from("request")); writeBytes(root,"pre/ollama-response.bin",Buffer.from("response"));
  write(root, "pre/ollama.json", { endpointHost: "127.0.0.1", socketRemoteAddress: "127.0.0.1", providerId: "ollama-loopback-base-mvp-v1", providerVersion: "1", model: "llama3.2:1b", observedModel: "llama3.2:1b", modelDigest: hash, requestArtifact: "pre/ollama-request.bin", responseArtifact: "pre/ollama-response.bin", requestSha256: sha256(Buffer.from("request")), responseSha256: sha256(Buffer.from("response")), requestedAt: "2026-07-21T00:00:00.000Z", respondedAt: "2026-07-21T00:00:01.000Z", candidateOnly: true, authorities: [] });
  const adapter=(interfaceGuid:string,type:string,status:string,publicRouteCapable=false)=>({interfaceGuid,interfaceIndex:type==="loopback"?1:2,name:type,description:type, type, operationalStatus:status, administrativeStatus:status, ipv4State:"bound",ipv6State:"bound",publicRouteCapable,inRestorationManifest:publicRouteCapable});
  write(root, "pre/network.json", { inventoryComplete: true, routes: [], adapters: [adapter("loop","loopback","enabled"),adapter("wifi","wifi","disabled",true)], publicDns: "FAILED", publicIpv4Tcp: "FAILED", publicIpv6: "UNAVAILABLE", publicHttp: "FAILED", publicHttps: "FAILED", localhost: "SUCCEEDED", ollama: "SUCCEEDED", desktopOperator: "SUCCEEDED" });
  write(root, "pre/desktop.json", { stages: visuals.map((stage) => ({ stage, imagePath: `visual/${stage}.png`, proofSid: sid, sessionId, releaseIdentity: "release-1", capturedAt: "2026-07-21T00:30:00.000Z" })) });
  write(root, "pre/persistence.json", { installationId: "install-1" });
  write(root, "post/restart.json", { sessionId, nonce, hostProfileId: "host-1", bootIdentityBefore: "boot-1", bootIdentityAfter: "boot-2", bootRecordBefore: "event-1", bootRecordAfter: "event-2", lastBootBefore: "2026-07-20T00:00:00.000Z", lastBootAfter: "2026-07-21T02:00:00.000Z", collectedBefore: "2026-07-21T01:00:00.000Z", collectedAfter: "2026-07-21T03:00:00.000Z", processIdBefore: 100, processIdAfter: 200 });
  write(root, "post/persistence.json", { installationId: "install-1", recovered: { state: true, history: true, artifact: true, evidence: true, preventionRule: true } });
  write(root, "post/recurrence.json", { exactFailurePrevention: "PASS", equivalentFailurePrevention: "PASS", relatedContextWarning: "PASS", outOfScopeNonBlocking: "PASS" });
  write(root, "negative-cases.json", { crossHostPortabilityClaimed: false, results: Object.fromEntries(RESTRICTED_USER_NEGATIVE_CASES.map((id) => [id, "PASS"])) });
  for (const stage of visuals) writeBytes(root, `visual/${stage}.png`, Buffer.from(`png:${stage}`));
  rebuild(root); return root;
}

function write(root: string, rel: string, value: any): void { const full = path.join(root, ...rel.split("/")); fs.mkdirSync(path.dirname(full), { recursive: true }); fs.writeFileSync(full, `${JSON.stringify(value)}\n`); }
function writeBytes(root: string, rel: string, value: Buffer): void { const full = path.join(root, ...rel.split("/")); fs.mkdirSync(path.dirname(full), { recursive: true }); fs.writeFileSync(full, value); }
function fileHash(root: string, rel: string): string { return sha256(fs.readFileSync(path.join(root, ...rel.split("/")))); }
function edit(root: string, rel: string, mutate: (v: any) => void): void { const full = path.join(root, ...rel.split("/")), value = JSON.parse(fs.readFileSync(full, "utf8")); mutate(value); fs.writeFileSync(full, `${JSON.stringify(value)}\n`); }
function rebuild(root: string): void {
  const prepPath = path.join(root, "preparation-manifest.json"), prep = JSON.parse(fs.readFileSync(prepPath, "utf8")); prep.governanceDecisionDigest = fileHash(root, "governance-decision.json"); fs.writeFileSync(prepPath, `${JSON.stringify(prep)}\n`);
  const files = walk(root).filter((p) => p !== EVIDENCE_MANIFEST_FILE).map((rel) => { const stat = fs.statSync(path.join(root, ...rel.split("/"))); return { path: rel, artifactType: rel.startsWith("visual/") ? "visual-capture" : "observation-json", collectorId: "synthetic-test-collector/v2", collectorSha256: collector, size: stat.size, sha256: fileHash(root, rel), capturedAt: "2026-07-21T00:00:00.000Z", proofStage: rel.startsWith("post/") ? "post-restart" : rel === "preparation-manifest.json" || rel === "governance-decision.json" ? "preparation" : "pre-restart", proofSid: sid, sessionId, nonce }; }).sort((a, b) => a.path.localeCompare(b.path));
  const body: any = { schemaVersion: EVIDENCE_MANIFEST_SCHEMA, profileId: RESTRICTED_USER_PROFILE_ID, evidenceMode: "synthetic-test-v2", sessionId, nonce, preparationManifestDigest: fileHash(root, "preparation-manifest.json"), governanceDecisionDigest: fileHash(root, "governance-decision.json"), files }; body.manifestDigest = manifestDigest(body); fs.writeFileSync(path.join(root, EVIDENCE_MANIFEST_FILE), `${JSON.stringify(body)}\n`);
}
function walk(root: string, dir = root): string[] { return fs.readdirSync(dir, { withFileTypes: true }).flatMap((e) => e.isDirectory() ? walk(root, path.join(dir, e.name)) : [path.relative(root, path.join(dir, e.name)).replace(/\\/g, "/")]); }

const cases: Array<[string, string, (root: string) => void]> = [
  ["development account", RESTRICTED_USER_REASON_CODES.developmentAccount, r => edit(r, "pre/account-token.json", v => v.proofSid = "S-1-5-21-1-2-3-1001")],
  ["administrator", RESTRICTED_USER_REASON_CODES.administrator, r => edit(r, "pre/account-token.json", v => v.tokenElevated = true)],
  ["Administrators group", RESTRICTED_USER_REASON_CODES.administratorsGroup, r => edit(r, "pre/account-token.json", v => v.enabledGroupSids.push("S-1-5-32-544"))],
  ["release inside repository", RESTRICTED_USER_REASON_CODES.releaseInsideRepository, r => edit(r, "pre/release-runtime.json", v => v.releaseRoot = "C:\\dev\\repo\\release path")],
  ["repository readable", RESTRICTED_USER_REASON_CODES.repositoryReadable, r => edit(r, "pre/source-denial.json", v => v.observations.find((x:any)=>x.targetRole==="repository-root"&&x.operation==="enumerate").classification="ENUMERABLE")],
  ["git readable", RESTRICTED_USER_REASON_CODES.gitReadable, r => edit(r, "pre/source-denial.json", v => v.observations.find((x:any)=>x.targetRole==="repository-git"&&x.operation==="known-child-read").classification="READABLE")],
  ["database readable", RESTRICTED_USER_REASON_CODES.databaseReadable, r => edit(r, "pre/source-denial.json", v => v.observations.find((x:any)=>x.targetRole==="development-sqlite"&&x.operation==="file-open").classification="READABLE")],
  ["development PATH", RESTRICTED_USER_REASON_CODES.inheritedPath, r => edit(r, "pre/environment.json", v => v.developmentPathPresent=true)],
  ["system Node", RESTRICTED_USER_REASON_CODES.systemNode, r => edit(r, "pre/release-runtime.json", v => v.execPath="C:\\Program Files\\nodejs\\node.exe")],
  ["Git process", RESTRICTED_USER_REASON_CODES.prohibitedProcess, r => edit(r, "pre/process-events.json", v => v.events.push({executableName:"git"}))],
  ["runtime missing", RESTRICTED_USER_REASON_CODES.runtimeMissing, r => edit(r, "pre/release-runtime.json", v => v.runtimeExists=false)],
  ["runtime altered", RESTRICTED_USER_REASON_CODES.runtimeAltered, r => edit(r, "pre/release-runtime.json", v => v.runtimeSha256="d".repeat(64))],
  ["public adapter", RESTRICTED_USER_REASON_CODES.publicAdapter, r => edit(r, "pre/network.json", v => v.adapters[1].administrativeStatus="enabled")],
  ["public reachable", RESTRICTED_USER_REASON_CODES.publicReachable, r => edit(r, "pre/network.json", v => v.publicHttps="SUCCEEDED")],
  ["remote Ollama", RESTRICTED_USER_REASON_CODES.ollamaRemote, r => edit(r, "pre/ollama.json", v => v.socketRemoteAddress="8.8.8.8")],
  ["model mismatch", RESTRICTED_USER_REASON_CODES.modelMismatch, r => edit(r, "pre/ollama.json", v => v.observedModel="other")],
  ["visual missing", RESTRICTED_USER_REASON_CODES.visualMissing, r => edit(r, "pre/desktop.json", v => v.stages.pop())],
  ["restart missing", RESTRICTED_USER_REASON_CODES.restartMissing, r => edit(r, "post/restart.json", v => v.bootIdentityAfter=v.bootIdentityBefore)],
  ["reparse escape", RESTRICTED_USER_REASON_CODES.pathEscape, r => edit(r, "pre/source-denial.json", v => v.observations[0].classification="REPARSE_ESCAPE")],
  ["cross-host claim", RESTRICTED_USER_REASON_CODES.crossHost, r => edit(r, "negative-cases.json", v => v.crossHostPortabilityClaimed=true)]
];

describe("observation-backed restricted-user proof v2", () => {
  it("never promotes a structurally complete synthetic bundle", () => { const result = verifyRestrictedUserEvidence(makeBundle()); expect(result.ok).toBe(false); expect(result.reasonCodes).toEqual(["SYNTHETIC_EVIDENCE_NON_PROMOTABLE"]); expect(result.grantedClaims).toEqual([]); });
  it("cannot promote a fixture by relabeling modes and collector identities", () => { const root=makeBundle(); edit(root,"preparation-manifest.json",v=>v.evidenceMode="governed-windows-v2"); rebuild(root); const p=path.join(root,EVIDENCE_MANIFEST_FILE),m=JSON.parse(fs.readFileSync(p,"utf8"));m.evidenceMode="governed-windows-v2";m.files.forEach((e:any)=>e.collectorId="sera-windows-collector/v2");const c={...m};delete c.manifestDigest;m.manifestDigest=manifestDigest(c);fs.writeFileSync(p,JSON.stringify(m));const result=verifyRestrictedUserEvidence(root);expect(result.ok).toBe(false);expect(result.reasonCodes).toContain("REAL_RELEASE_ZIP_MISSING");expect(result.grantedClaims).toEqual([]); });
  it("does not accept an object or absent bundle", () => { expect(proveRestrictedUserEvidence().reasonCodes).toContain("REAL_EVIDENCE_BUNDLE_REQUIRED"); });
  it.each(cases)("returns a precise reason for %s", (_name, reason, mutate) => { const root = makeBundle(); mutate(root); rebuild(root); expect(verifyRestrictedUserEvidence(root).reasonCodes).toContain(reason); });
  it("detects digest mismatch", () => { const root = makeBundle(); fs.appendFileSync(path.join(root, "pre", "network.json"), "x"); expect(verifyRestrictedUserEvidence(root).reasonCodes).toContain("ARTIFACT_DIGEST_MISMATCH:pre/network.json"); });
  it("rejects an unreferenced artifact", () => { const root=makeBundle();fs.writeFileSync(path.join(root,"extra.json"),"{}\n");expect(verifyRestrictedUserEvidence(root).reasonCodes).toContain("UNREFERENCED_OR_MISSING_ARTIFACT"); });
  it("detects byte-size mismatch", () => { const root = makeBundle(), p = path.join(root, EVIDENCE_MANIFEST_FILE), m = JSON.parse(fs.readFileSync(p,"utf8")); m.files[0].size++; const c={...m}; delete c.manifestDigest; m.manifestDigest=manifestDigest(c); fs.writeFileSync(p,JSON.stringify(m)); expect(verifyRestrictedUserEvidence(root).reasonCodes.some(x=>x.startsWith("ARTIFACT_SIZE_MISMATCH"))).toBe(true); });
  it("detects nonce, collector, duplicate, monitor, and secret violations", () => { for (const [reason, mutate] of [["SESSION_BINDING_MISMATCH",(m:any)=>m.files[0].nonce="bad"],["COLLECTOR_DIGEST_MISMATCH",(m:any)=>m.files[0].collectorSha256="d".repeat(64)],["DUPLICATE_ARTIFACT",(m:any)=>m.files.push({...m.files[0]})]] as any) { const root=makeBundle(),p=path.join(root,EVIDENCE_MANIFEST_FILE),m=JSON.parse(fs.readFileSync(p,"utf8")); mutate(m); const c={...m};delete c.manifestDigest;m.manifestDigest=manifestDigest(c);fs.writeFileSync(p,JSON.stringify(m));expect(verifyRestrictedUserEvidence(root).reasonCodes).toContain(reason); } const gap=makeBundle();edit(gap,"pre/process-events.json",v=>v.readyHandshake=false);rebuild(gap);expect(verifyRestrictedUserEvidence(gap).reasonCodes).toContain("PROCESS_MONITOR_INCOMPLETE"); const secret=makeBundle();edit(secret,"pre/environment.json",v=>v.entries[0].value="secret");rebuild(secret);expect(verifyRestrictedUserEvidence(secret).reasonCodes).toContain(RESTRICTED_USER_REASON_CODES.inheritedPath); });
  it("rejects command injection at the executable launch seam", () => { expect(runWindowsCommand(WINDOWS_TOOLS.whoami, ["/user & calc"]).failure).toBe("ARGUMENT_REJECTED"); });
});
