import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { describe, expect, it } from "vitest";
import { ProofProcessMonitor, WINDOWS_TOOLS, buildPortableBaseMvp, buildSanitizedEnvironment, captureVisual, collectAccountObservation, collectAdapterInventory, collectBootObservation, collectDenialObservations, collectPostRestart, collectPreRestart, collectReleaseObservation, compareBootObservations, finalizeEvidenceManifest, manifestDigest, observeOllama, observeRedactedEnvironment, parseWhoamiGroups, parseWhoamiUser, runWindowsCommand, sha256, sha256File, writeEvidenceArtifact } from "@sera/portable-base-mvp";

const sid="S-1-5-21-1-2-3-1002",devSid="S-1-5-21-1-2-3-1001",hash="a".repeat(64);
const command=(stdout="",failure="NONE")=>({executable:WINDOWS_TOOLS.whoami,args:[],startedAt:new Date().toISOString(),completedAt:new Date().toISOString(),exitCode:failure==="NONE"?0:1,stdout,stderr:"",failure,timedOut:failure==="TIMEOUT"}) as any;
function accountRun(overrides:{user?:string;groups?:string}={}){return (exe:string,args:string[])=>exe===WINDOWS_TOOLS.powershell?command(JSON.stringify({name:"proof",sid,enabled:true,principalSource:"Local",profilePath:process.env.USERPROFILE??os.homedir(),profileLastUse:"2026-07-21T00:00:00.000Z"})):args.includes("/user")?command(overrides.user??`"HOST\\proof","${sid}"\r\n`):args.includes("/groups")?command(overrides.groups??`"Users","S-1-5-32-545","Alias","Mandatory group, Enabled by default, Enabled group"\r\n`):command(`"Privilege","Description","Disabled"\r\n`) as any;}

describe("real restricted-user collectors v3",()=>{
  it("allows only explicit executables",()=>{expect(runWindowsCommand("cmd.exe",[]).failure).toBe("NOT_ALLOWLISTED");});
  it("rejects argument injection",()=>{expect(runWindowsCommand(WINDOWS_TOOLS.whoami,["/user & calc"]).failure).toBe("ARGUMENT_REJECTED");});
  it("classifies timeout",()=>{const spawn=(()=>({status:null,stdout:"",stderr:"",error:Object.assign(new Error(),{code:"ETIMEDOUT"})})) as any;expect(runWindowsCommand(WINDOWS_TOOLS.whoami,["/user"],{spawn}).failure).toBe("TIMEOUT");});
  it("parses whoami identity",()=>{expect(parseWhoamiUser(`"HOST\\proof","${sid}"\r\n`)).toEqual({username:"HOST\\proof",sid});});
  it("parses enabled token groups",()=>{expect(parseWhoamiGroups(`"Users","S-1-5-32-545","Alias","Enabled group"\r\n`)[0].enabled).toBe(true);});
  it("collects a normalized limited account",()=>{expect(collectAccountObservation({expectedSid:sid,developmentSid:devSid,expectedAccount:"proof",run:accountRun() as any}).normalized.proofSid).toBe(sid);});
  it("rejects SID mismatch",()=>{expect(()=>collectAccountObservation({expectedSid:"S-1-5-9",developmentSid:devSid,expectedAccount:"proof",run:accountRun() as any})).toThrow("ACTIVE_SID_MISMATCH");});
  it("rejects elevated Administrators group",()=>{const groups=`"Administrators","S-1-5-32-544","Alias","Enabled group"\r\n`;expect(()=>collectAccountObservation({expectedSid:sid,developmentSid:devSid,expectedAccount:"proof",run:accountRun({groups}) as any})).toThrow("ELEVATED_TOKEN_REJECTED");});
  it("distinguishes readable and absent filesystem targets",()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),"sera-probe-"));fs.writeFileSync(path.join(root,"known.txt"),"x");const rows=collectDenialObservations([{targetRole:"repo",requestedPath:root,knownChild:"known.txt"},{targetRole:"old",requestedPath:path.join(root,"absent")}],sid);expect(rows.some(r=>r.targetRole==="repo"&&["READABLE","ENUMERABLE"].includes(r.classification))).toBe(true);expect(rows.filter(r=>r.targetRole==="old").every(r=>r.classification==="ABSENT")).toBe(true);});
  it("detects a reparse escape when supported",()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),"sera-link-")),outside=fs.mkdtempSync(path.join(os.tmpdir(),"sera-out-")),link=path.join(root,"link");try{fs.symlinkSync(outside,link,"junction");expect(collectDenialObservations([{targetRole:"repo",requestedPath:link}],sid).some(r=>r.classification==="REPARSE_ESCAPE")).toBe(true);}catch{expect(true).toBe(true);}});
  it("verifies release ZIP, tree, runtime path and digest through bundled execution",()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),"sera collector release ")),release=buildPortableBaseMvp({projectRoot:process.cwd(),outputRoot:root}),manifest=JSON.parse(fs.readFileSync(release.manifestPath,"utf8")),prep={release:{expectedExtractionRoot:release.packageRoot,releaseManifestPath:release.manifestPath,zipPath:release.zipPath},repository:{canonicalPath:path.join(root,"unrelated-repository")}};const observed=collectReleaseObservation({preparation:prep,proofSid:sid,sessionId:"s"});expect(observed.zipSha256).toBe(sha256File(release.zipPath));expect(observed.runtimeSha256).toBe(manifest.runtime.sha256);expect(observed.execPath).toBe(observed.runtimePath);},30_000);
  it("process monitor emits handshake and prohibited observation",()=>{const monitor=new ProofProcessMonitor("s","n",sid);monitor.record({timestamp:new Date().toISOString(),pid:2,parentPid:1,executableName:"git.exe",executablePath:"C:\\git.exe"});const result=monitor.stop();expect(result.readyHandshake).toBe(true);expect(result.events[0].prohibited).toBe(true);});
  it("process interruption marks incomplete",()=>{const monitor=new ProofProcessMonitor("s","n",sid);monitor.markInterrupted();expect(monitor.stop().completeness).toBe("INTERRUPTED");});
  it("builds environment from an allowlist",()=>{const env=buildSanitizedEnvironment({SystemRoot:"C:\\Windows",SECRET:"no",PATH:"dev"},"C:\\release runtime");expect(env.PATH).toBe("C:\\release runtime");expect(env.SECRET).toBeUndefined();});
  it("redacts environment values",()=>{const record=observeRedactedEnvironment({PATH:"C:\\runtime",TOKEN:"top-secret-value"},1,"s",["C:\\dev"]),serialized=JSON.stringify(record);expect(serialized).not.toContain("top-secret-value");expect(serialized).not.toContain('"TOKEN"');expect(record.secretValueWritten).toBe(false);});
  it("rejects nonliteral-loopback Ollama",async()=>{await expect(observeOllama({endpoint:"http://localhost:11434/api/generate",requestBytes:Buffer.from("x")})).rejects.toThrow("OLLAMA_ENDPOINT_NOT_LITERAL_LOOPBACK");});
  it("parses complete adapter inventory",()=>{const payload={adapters:[{interfaceGuid:"g",interfaceIndex:1,name:"Loopback",description:"Loopback",type:"loopback",operationalStatus:"up",administrativeStatus:"enabled",ipv4State:"Connected",ipv6State:"Connected"}],routes:[]};const run=(()=>({...command(JSON.stringify(payload)),executable:WINDOWS_TOOLS.powershell})) as any;expect(collectAdapterInventory(run).inventoryComplete).toBe(true);});
  it("creates PNG bytes and stage metadata from injected pixels",()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),"sera-visual-")),png=Buffer.from([137,80,78,71,1]);const result=captureVisual({root,stage:"runtime-health",proofSid:sid,sessionId:"s",nonce:"n",releaseIdentity:"r",imageSource:()=>png});expect(fs.readFileSync(path.join(root,result.imagePath))).toEqual(png);expect(result.sha256).toBe(sha256(png));});
  it("rejects unknown and duplicate visual stages",()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),"sera-visual-neg-")),base={root,proofSid:sid,sessionId:"s",nonce:"n",releaseIdentity:"r",imageSource:()=>Buffer.from("png")};expect(()=>captureVisual({...base,stage:"unknown"})).toThrow("UNKNOWN_VISUAL_STAGE");captureVisual({...base,stage:"health".replace("health","runtime-health")});expect(()=>captureVisual({...base,stage:"runtime-health"})).toThrow("DUPLICATE_VISUAL_STAGE");});
  it("parses boot observation and rejects unchanged boot",()=>{const run=(()=>({...command(JSON.stringify({lastBoot:"2026-07-21T00:00:00.000Z",bootRecord:"1"})),executable:WINDOWS_TOOLS.powershell})) as any,before=collectBootObservation({hostProfileId:"h",installationId:"i",sessionId:"s",nonce:"n",processId:1,run}),after={...before,processId:2,collectedAt:"2026-07-21T01:00:00.000Z"};expect(()=>compareBootObservations(before,after)).toThrow("WINDOWS_BOOT_IDENTITY_UNCHANGED");});
  it("accepts continuous changed boot observations",()=>{const before={hostProfileId:"h",installationId:"i",sessionId:"s",nonce:"n",processId:1,bootIdentity:"b1",bootRecord:"1",lastBoot:"2026-07-20T00:00:00Z",collectedAt:"2026-07-20T01:00:00Z"},after={...before,processId:2,bootIdentity:"b2",bootRecord:"2",lastBoot:"2026-07-21T00:00:00Z",collectedAt:"2026-07-21T01:00:00Z"};expect(compareBootObservations(before,after).bootIdentityAfter).toBe("b2");});
  it("writes artifacts and finalizes deterministic manifest",()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),"sera-finalize-"));writeEvidenceArtifact(root,"pre/a.json",{a:1});writeEvidenceArtifact(root,"post/b.json",{b:2});const manifest=finalizeEvidenceManifest({root,profileId:"p",evidenceMode:"synthetic-test-v2",sessionId:"s",nonce:"n",proofSid:sid,collectorId:"test",collectorSha256:hash,preparationManifestDigest:hash,governanceDecisionDigest:hash,stageFor:p=>p.startsWith("post/")?"post-restart":"pre-restart"});expect(manifest.files.map((x:any)=>x.path)).toEqual(["post/b.json","pre/a.json"]);const copy={...manifest};delete copy.manifestDigest;expect(manifest.manifestDigest).toBe(manifestDigest(copy));});
  it("rejects duplicate artifact writes",()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),"sera-write-neg-"));writeEvidenceArtifact(root,"a.json",{});expect(()=>writeEvidenceArtifact(root,"a.json",{})).toThrow("DUPLICATE_ARTIFACT");});
  it("guardedly refuses pre-restart collection under the development account",async()=>{if(process.platform!=="win32")return;const root=fs.mkdtempSync(path.join(os.tmpdir(),"sera-guard-pre-")),file=path.join(root,"preparation-manifest.json");fs.writeFileSync(file,JSON.stringify({expectedProofSid:"S-1-5-21-0-0-0-9999",developmentSid:sid,expectedProofAccountName:"SERA_PROOF_ACCOUNT_THAT_DOES_NOT_EXIST"}));await expect(collectPreRestart(file)).rejects.toMatchObject({name:"Error",code:expect.any(String)});});
  it("guardedly refuses post-restart collection without a boot change",()=>{if(process.platform!=="win32")return;const root=fs.mkdtempSync(path.join(os.tmpdir(),"sera-guard-post-")),prep=path.join(root,"preparation-manifest.json"),before=collectBootObservation({hostProfileId:"host",installationId:"install",sessionId:"session",nonce:"nonce",processId:process.pid});fs.mkdirSync(path.join(root,"pre"));fs.writeFileSync(prep,JSON.stringify({hostProfileId:"host",sessionId:"session",nonce:"nonce"}));fs.writeFileSync(path.join(root,"pre","boot.json"),JSON.stringify(before));fs.writeFileSync(path.join(root,"pre","release-runtime.json"),JSON.stringify({pid:process.pid}));expect(()=>collectPostRestart(prep)).toThrow(/boot change/i);});
});
