import crypto from "node:crypto";import fs from "node:fs";import os from "node:os";import path from "node:path";import {afterEach,describe,expect,it} from "vitest";
import {auditIdentityBindings,IDENTITY_BINDING_SCHEMA} from "../packages/portable-base-mvp/src/restricted-user-identity-binding";import {emitObserverBootStage,emitSubjectBindingRecords,prepareProductionIdentityBindings,readVerifiedInstallationIdentity} from "../packages/portable-base-mvp/src/restricted-user-production-bindings";import {finalizeEvidenceManifest} from "../packages/portable-base-mvp/src/restricted-user-writer";import {normalizedTreeDigest,sha256File} from "../packages/portable-base-mvp/src/restricted-user-evidence";
const roots:string[]=[];const write=(p:string,v:string)=>{fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,v)};
function fixture(){const base=fs.mkdtempSync(path.join(os.tmpdir(),"sera-v54-"));roots.push(base);const repo=path.join(base,"repo"),release=path.join(base,"release"),evidence=path.join(base,"proof"),observer=path.join(base,"observer"),collector=path.join(release,"collectors","restricted-user-collector.cjs"),runtime=path.join(release,"runtime","node.exe"),zip=path.join(base,"release.zip"),gov=path.join(base,"gov.json"),manifestPath=path.join(release,"release-manifest.json");write(path.join(repo,".git","HEAD"),"ref");write(collector,"collector-v54");write(runtime,"runtime-v54");write(zip,"zip");write(gov,"{}");const manifest:any={version:"release-v54",files:[{path:"collectors/restricted-user-collector.cjs",size:fs.statSync(collector).size,sha256:sha256File(collector)}],runtime:{path:"runtime/node.exe",size:fs.statSync(runtime).size,sha256:sha256File(runtime)}};write(manifestPath,JSON.stringify(manifest));fs.mkdirSync(observer);fs.mkdirSync(evidence);const prepPath=path.join(evidence,"preparation-manifest.json"),prep:any={schemaVersion:"sera.restricted-user-preparation-manifest.v5.2",profileId:"same-host-restricted-user-release-only-v1",observerRoot:observer,sessionId:"session",nonce:"nonce",hostProfileId:"host",expectedProofSid:"sid",repository:{canonicalPath:repo},release:{zipPath:zip,zipSha256:sha256File(zip),expectedExtractionRoot:release,extractedTreeDigest:normalizedTreeDigest(release),releaseManifestPath:manifestPath,releaseManifestDigest:sha256File(manifestPath),runtimePath:runtime}};write(prepPath,JSON.stringify(prep));const prepared=prepareProductionIdentityBindings(prepPath,{uuid:()=>"00000000-0000-4000-8000-000000000054",now:()=>"2026-07-20T00:00:00Z"}),preBoot={bootIdentity:"boot-a",lastBoot:"2026-07-20T00:00:00Z",bootRecord:"10",collectedAt:"2026-07-20T01:00:00Z"},postBoot={bootIdentity:"boot-b",lastBoot:"2026-07-21T00:00:00Z",bootRecord:"11",collectedAt:"2026-07-21T01:00:00Z"},proc={runtimePath:runtime,processId:10,parentProcessId:1,proofSid:"sid",windowsSessionId:2};return{base,repo,release,evidence,observer,collector,runtime,manifest,prepPath,prepared,preBoot,postBoot,proc}}
function emit(f:any){const sp=emitSubjectBindingRecords(f.evidence,f.prepared,"PRE_RESTART",f.preBoot,f.proc),op=emitObserverBootStage(f.observer,f.prepared,"PRE_RESTART",f.preBoot,{observerSha256:"a".repeat(64),observerPath:path.join(f.release,"collectors","privileged-observer.cjs"),monitorSha256:"b".repeat(64),observerSid:"observer",pid:20,windowsSessionId:1,observerReadyAt:"2026-07-20T00:59:00Z"}),os=emitObserverBootStage(f.observer,f.prepared,"POST_RESTART",f.postBoot,{observerSha256:"a".repeat(64),observerPath:path.join(f.release,"collectors","privileged-observer.cjs"),monitorSha256:"b".repeat(64),observerSid:"observer",pid:40,windowsSessionId:1,observerReadyAt:"2026-07-21T00:59:00Z"}),ss=emitSubjectBindingRecords(f.evidence,f.prepared,"POST_RESTART",f.postBoot,{...f.proc,processId:30});return{sp,op,ss,os}}
function audit(f:any,x:any,manifest:any={installationIdentity:f.prepared.installationIdentity,subjectCollectorDigest:f.prepared.subjectCollector.sha256}){return auditIdentityBindings({schemaVersion:IDENTITY_BINDING_SCHEMA,preparation:f.prepared,manifest,releaseRoot:f.release,repositoryRoot:f.repo,releaseManifest:f.manifest,subjectCollector:{relativePath:f.prepared.subjectCollector.relativePath,canonicalPath:f.collector,size:fs.statSync(f.collector).size,sha256:sha256File(f.collector),releaseManifestMember:true,extractedTreeMember:true,runtimePath:f.runtime},subjectPre:x.sp.bootStage,observerPre:x.op,subjectPost:x.ss.bootStage,observerPost:x.os,subsetClaims:[],requestedClaims:[]})}
afterEach(()=>{for(const r of roots.splice(0))fs.rmSync(r,{recursive:true,force:true})});describe("production identity-binding emission v5.4",()=>{
 it("creates installation identity once and reuses it",()=>{const f=fixture(),a=readVerifiedInstallationIdentity(f.prepared),again=prepareProductionIdentityBindings(f.prepPath,{uuid:()=>crypto.randomUUID()});expect(again.installationIdentity).toBe(a.installationId)});
 it("post collection cannot regenerate installation identity",()=>{const f=fixture();fs.rmSync(f.prepared.installationIdentityRecord.path);expect(()=>emitSubjectBindingRecords(f.evidence,f.prepared,"POST_RESTART",f.postBoot,f.proc)).toThrow("ENOENT")});
 it("emits matching subject collector identities",()=>{const f=fixture(),x=emit(f);expect(x.sp.collector.sha256).toBe(x.ss.collector.sha256);expect(x.sp.collector.canonicalPath).toBe(f.collector)});
 it("emits compatible observer stage records",()=>{const f=fixture(),x=emit(f);expect(x.op.stage).toBe("PRE_RESTART");expect(x.os.stage).toBe("POST_RESTART");expect(x.op.subjectCollectorDigest).toBe(x.sp.bootStage.subjectCollectorDigest)});
 it("matches subject and observer within both stages",()=>{const f=fixture(),x=emit(f);expect(x.sp.bootStage.bootIdentity).toBe(x.op.bootIdentity);expect(x.ss.bootStage.bootIdentity).toBe(x.os.bootIdentity)});
 it("requires a changed later boot",()=>{const f=fixture(),x=emit(f),r=audit(f,x);expect(r.reasonCodes).toEqual([]);expect(r.windowsRestartVerified).toBe(true)});
 it("production artifacts satisfy the existing V5.3 auditor",()=>{const f=fixture(),x=emit(f);expect(audit(f,x)).toMatchObject({installationIdentityVerified:true,subjectCollectorVerified:true,preRestartBootStageVerified:true,postRestartBootStageVerified:true})});
 it("immutable manifest registers every generated subject artifact",()=>{const f=fixture();emit(f);write(path.join(f.evidence,"governance-decision.json"),"{}");const m=finalizeEvidenceManifest({root:f.evidence,profileId:f.prepared.profileId,evidenceMode:"synthetic-test-v2",sessionId:"session",nonce:"nonce",proofSid:"sid",collectorId:"sera-windows-collector/v4",collectorSha256:f.prepared.subjectCollector.sha256,installationIdentity:f.prepared.installationIdentity,installationIdentityRecordDigest:f.prepared.installationIdentityRecord.sha256,subjectCollectorDigest:f.prepared.subjectCollector.sha256,preparationManifestDigest:sha256File(f.prepPath),governanceDecisionDigest:sha256File(path.join(f.evidence,"governance-decision.json")),stageFor:p=>p.startsWith("post/")?"post-restart":p.startsWith("pre/")?"pre-restart":"preparation"});expect(m.files.map((e:any)=>e.path)).toEqual(expect.arrayContaining(["pre/subject-collector-identity.json","post/subject-collector-identity.json","pre/boot-stage.json","post/boot-stage.json"]));expect(m.installationIdentity).toBe(f.prepared.installationIdentity)});
 it("removing a binding artifact blocks disk consumption",()=>{const f=fixture();emit(f);fs.rmSync(path.join(f.evidence,"pre","boot-stage.json"));expect(fs.existsSync(path.join(f.evidence,"pre","boot-stage.json"))).toBe(false)});
 it("altering a generated artifact changes its digest",()=>{const f=fixture();emit(f);const p=path.join(f.evidence,"pre","boot-stage.json"),before=sha256File(p);fs.appendFileSync(p,"x");expect(sha256File(p)).not.toBe(before)});
 it("regenerated installation identity blocks",()=>{const f=fixture(),x=emit(f);x.ss.bootStage.installationIdentity="replacement";expect(audit(f,x).reasonCodes).toContain("INSTALLATION_IDENTITY_MISMATCH")});
 it("changed collector digest blocks",()=>{const f=fixture(),x=emit(f);x.ss.bootStage.subjectCollectorDigest="f".repeat(64);expect(audit(f,x).reasonCodes).toContain("SUBJECT_COLLECTOR_PRE_POST_MISMATCH")});
 it("subject observer boot mismatch blocks",()=>{const f=fixture(),x=emit(f);x.op.bootIdentity="wrong";expect(audit(f,x).reasonCodes).toContain("BOOT_STAGE_PAIR_MISMATCH")});
 it("replayed pre evidence blocks",()=>{const f=fixture(),x=emit(f);x.ss.bootStage.collectionTimestamp=x.sp.bootStage.collectionTimestamp;expect(audit(f,x).reasonCodes).toContain("BOOT_STAGE_REPLAY_DETECTED")});
});
