import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { describe, expect, it } from "vitest";
import { createDefaultPhaseFactoryAlphaV1, inspectPhaseFactoryAlphaV1, runPhaseFactoryAlphaV1 } from "../../scripts/lib/phase-factory-alpha-v1.mjs";

function tempRoot(name: string) {
  return fs.mkdtempSync(path.join(os.tmpdir(), `sera-${name}-`));
}

describe("Phase 100H — Phase Factory Alpha v1", () => {
  it("produces owner-review Phase Factory Alpha evidence without mutation or execution", () => {
    const artifactRoot = tempRoot("phase100h-phase-factory-alpha");
    const result = runPhaseFactoryAlphaV1(createDefaultPhaseFactoryAlphaV1(), { artifactRoot });
    expect(result.ok).toBe(true);
    expect(result.phaseFactoryAlphaStatus).toBe("phase-factory-alpha-ready");
    expect(result.validationFailedCount).toBe(0);
    expect(result.declaredFileCount).toBe(5);
    expect(result.phaseFactoryAlphaRequirementCount).toBe(38);
    expect(result.phaseFactoryAlphaFieldCount).toBe(74);
    expect(result.phaseFactoryStageCount).toBe(8);
    expect(result.phaseFactoryIntegrationCount).toBe(8);
    expect(result.roadmapTrackCount).toBe(13);
    expect(result.multiLanguageProductionTargetCount).toBe(18);
    expect(result.safetyGateCount).toBe(1800);
    expect(result.phaseFactoryAlphaAllowed).toBe(true);
    expect(result.phaseBacklogReadAllowed).toBe(true);
    expect(result.phaseSpecReadAllowed).toBe(true);
    expect(result.phaseOverlayManifestReadAllowed).toBe(true);
    expect(result.phaseZipValidationReadAllowed).toBe(true);
    expect(result.phaseApplyQueueReadAllowed).toBe(true);
    expect(result.phaseTroubleshootingReadAllowed).toBe(true);
    expect(result.phaseEvidencePackReadAllowed).toBe(true);
    expect(result.ownerReviewAlphaPacketAllowed).toBe(true);
    expect(result.autoRunFuturePhasesAllowed).toBe(false);
    expect(result.projectRepoSourceMutated).toBe(false);
    expect(result.futurePhaseAutoRunExecuted).toBe(false);
    expect(result.autoFixExecuted).toBe(false);
    expect(result.applyExecuted).toBe(false);
    expect(result.patchExecuted).toBe(false);
    expect(result.realProjectBranchCreated).toBe(false);
    expect(result.realProjectMergePerformed).toBe(false);
    expect(result.phaseFactoryAlphaIntegrated).toBe(true);
    expect(result.alphaManifestProduced).toBe(true);
    expect(result.ownerReviewManifestProduced).toBe(true);
    expect(result.readyForOwnerReview).toBe(true);
    expect(fs.existsSync(result.packetPath)).toBe(true);
    expect(fs.existsSync(result.alphaManifestPath)).toBe(true);
    expect(fs.existsSync(result.ownerReviewManifestPath)).toBe(true);
  });

  it("requires Phase 100A through Phase 100G lineage and Tyler approval", () => {
    const config = createDefaultPhaseFactoryAlphaV1();
    config.phase100GPhaseEvidencePackReady = false;
    config.sourceEvidencePackId = "wrong-pack";
    config.phaseLineageReady.phase100AReady = false;
    config.phaseLineageReady.phase100GReady = false;
    config.approvalRecord.approved = false;
    config.approvalRecord.selfApproved = true;
    const result = inspectPhaseFactoryAlphaV1(config);
    expect(result.ok).toBe(false);
    expect(result.blockers).toContain("Phase 100G evidence pack must be ready before Phase 100H Alpha.");
    expect(result.blockers).toContain("Phase 100H must link to the Phase 100G evidence pack.");
    expect(result.blockers).toContain("phase100AReady must be true for Phase 100H Alpha.");
    expect(result.blockers).toContain("phase100GReady must be true for Phase 100H Alpha.");
    expect(result.blockers).toContain("Tyler Wallace approval record is required for Phase 100H Alpha.");
    expect(result.blockers).toContain("Self-approval is blocked for Phase 100H Alpha.");
  });

  it("fails closed for unsafe or incomplete integration items", () => {
    const config = createDefaultPhaseFactoryAlphaV1();
    config.phaseFactoryIntegrationItems[0].phaseId = "101";
    config.phaseFactoryIntegrationItems[0].lineageId = "wrong";
    config.phaseFactoryIntegrationItems[0].integrationStatus = "action-ready";
    config.phaseFactoryIntegrationItems[0].lineageReady = false;
    config.phaseFactoryIntegrationItems[0].ownerReviewRequired = false;
    config.phaseFactoryIntegrationItems[0].futurePhaseAutoRunAllowed = true;
    config.phaseFactoryIntegrationItems[0].autoFixAllowed = true;
    config.phaseFactoryIntegrationItems[0].applyExecutionAllowed = true;
    config.phaseFactoryIntegrationItems[0].sourceMutationAllowed = true;
    config.phaseFactoryIntegrationItems[0].evidenceLinks = ["../unsafe.txt"];
    const result = inspectPhaseFactoryAlphaV1(config);
    expect(result.ok).toBe(false);
    expect(result.blockers.some((blocker: string) => blocker.includes("phaseId"))).toBe(true);
    expect(result.blockers.some((blocker: string) => blocker.includes("expected lineage id"))).toBe(true);
    expect(result.blockers.some((blocker: string) => blocker.includes("owner-review-alpha-integrated"))).toBe(true);
    expect(result.blockers.some((blocker: string) => blocker.includes("lineageReady"))).toBe(true);
    expect(result.blockers.some((blocker: string) => blocker.includes("ownerReviewRequired"))).toBe(true);
    expect(result.blockers.some((blocker: string) => blocker.includes("futurePhaseAutoRunAllowed"))).toBe(true);
    expect(result.blockers.some((blocker: string) => blocker.includes("autoFixAllowed"))).toBe(true);
    expect(result.blockers.some((blocker: string) => blocker.includes("applyExecutionAllowed"))).toBe(true);
    expect(result.blockers.some((blocker: string) => blocker.includes("sourceMutationAllowed"))).toBe(true);
    expect(result.blockers.some((blocker: string) => blocker.includes("safe relative path"))).toBe(true);
  });

  it("blocks unsafe future auto-run, autofix, apply, project, Git, shell, scheduler, fleet, and self-governance powers", () => {
    const config = createDefaultPhaseFactoryAlphaV1();
    config.boundaries.autoRunFuturePhasesAllowed = true;
    config.boundaries.autoFixAllowed = true;
    config.boundaries.applyExecutionAllowed = true;
    config.boundaries.patchExecutionAllowed = true;
    config.boundaries.projectRepoSourceMutationAllowed = true;
    config.boundaries.realProjectBranchCreationAllowed = true;
    config.boundaries.realProjectMergeExecutionAllowed = true;
    config.boundaries.gitPushAllowed = true;
    config.boundaries.tagCreationAllowed = true;
    config.boundaries.arbitraryCommandAllowed = true;
    config.boundaries.shellExecutionAllowed = true;
    config.boundaries.schedulerWorkflowMutationAllowed = true;
    config.boundaries.iPhoneAutomationMutationAllowed = true;
    config.boundaries.fleetExecutionAllowed = true;
    config.boundaries.awayModeExecutionAllowed = true;
    config.boundaries.selfApprovalAllowed = true;
    config.boundaries.selfMergeAllowed = true;
    config.boundaries.selfDeployAllowed = true;
    config.boundaries.productionDeploymentAllowed = true;
    config.projectRepoSourceMutated = true;
    config.futurePhaseAutoRunExecuted = true;
    config.autoFixExecuted = true;
    config.applyExecuted = true;
    config.patchExecuted = true;
    const result = inspectPhaseFactoryAlphaV1(config);
    expect(result.ok).toBe(false);
    expect(result.blockers).toContain("autoRunFuturePhasesAllowed must remain false");
    expect(result.blockers).toContain("autoFixAllowed must remain false");
    expect(result.blockers).toContain("applyExecutionAllowed must remain false");
    expect(result.blockers).toContain("patchExecutionAllowed must remain false");
    expect(result.blockers).toContain("projectRepoSourceMutationAllowed must remain false");
    expect(result.blockers).toContain("realProjectBranchCreationAllowed must remain false");
    expect(result.blockers).toContain("realProjectMergeExecutionAllowed must remain false");
    expect(result.blockers).toContain("gitPushAllowed must remain false");
    expect(result.blockers).toContain("tagCreationAllowed must remain false");
    expect(result.blockers).toContain("arbitraryCommandAllowed must remain false");
    expect(result.blockers).toContain("shellExecutionAllowed must remain false");
    expect(result.blockers).toContain("schedulerWorkflowMutationAllowed must remain false");
    expect(result.blockers).toContain("iPhoneAutomationMutationAllowed must remain false");
    expect(result.blockers).toContain("fleetExecutionAllowed must remain false");
    expect(result.blockers).toContain("awayModeExecutionAllowed must remain false");
    expect(result.blockers).toContain("selfApprovalAllowed must remain false");
    expect(result.blockers).toContain("selfMergeAllowed must remain false");
    expect(result.blockers).toContain("selfDeployAllowed must remain false");
    expect(result.blockers).toContain("productionDeploymentAllowed must remain false");
    expect(result.blockers).toContain("projectRepoSourceMutated must remain false");
    expect(result.blockers).toContain("futurePhaseAutoRunExecuted must remain false");
    expect(result.blockers).toContain("autoFixExecuted must remain false");
    expect(result.blockers).toContain("applyExecuted must remain false");
    expect(result.blockers).toContain("patchExecuted must remain false");
  });

  it("records validation failure evidence when alpha integration counts do not match expectations", () => {
    const artifactRoot = tempRoot("phase100h-phase-factory-alpha-failure");
    const config = createDefaultPhaseFactoryAlphaV1({ expectedPhaseFactoryIntegrationCount: 99 });
    const result = runPhaseFactoryAlphaV1(config, { artifactRoot });
    expect(result.ok).toBe(false);
    expect(result.validationFailedCount).toBe(1);
    expect(result.phaseFactoryAlphaIntegrated).toBe(false);
    expect(result.readyForOwnerReview).toBe(false);
    expect(result.projectRepoSourceMutated).toBe(false);
    expect(result.futurePhaseAutoRunExecuted).toBe(false);
    expect(result.autoFixExecuted).toBe(false);
    expect(result.applyExecuted).toBe(false);
    expect(result.patchExecuted).toBe(false);
    const packet = JSON.parse(fs.readFileSync(result.packetPath, "utf8"));
    expect(packet.status).toBe("phase-factory-alpha-validation-failed");
    expect(packet.phaseFactoryAlphaIntegrated).toBe(false);
    expect(packet.ownerReviewManifest.readyForOwnerReview).toBe(false);
    expect(packet.checks.filter((check: { passed: boolean }) => !check.passed).length).toBe(0);
  });
});
