import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { describe, expect, it } from "vitest";
import { createDefaultWorkerCapabilityCardsV1, inspectWorkerCapabilityCardsV1, runWorkerCapabilityCardsV1 } from "../../scripts/lib/worker-capability-cards-v1.mjs";

function tempRoot(name: string) {
  return fs.mkdtempSync(path.join(os.tmpdir(), `sera-${name}-`));
}

describe("Phase 102 — Worker Capability Cards v1", () => {
  it("produces owner-review worker capability card evidence without execution", () => {
    const artifactRoot = tempRoot("phase102-worker-capability-cards");
    const result = runWorkerCapabilityCardsV1(createDefaultWorkerCapabilityCardsV1(), { artifactRoot });
    expect(result.ok).toBe(true);
    expect(result.workerCapabilityCardsStatus).toBe("worker-capability-cards-ready");
    expect(result.validationFailedCount).toBe(0);
    expect(result.declaredFileCount).toBe(5);
    expect(result.workerCapabilityCardsRequirementCount).toBe(42);
    expect(result.workerCapabilityCardsFieldCount).toBe(84);
    expect(result.workerCapabilityCardCount).toBe(12);
    expect(result.inputContractCount).toBe(12);
    expect(result.outputContractCount).toBe(12);
    expect(result.roadmapTrackCount).toBe(13);
    expect(result.multiLanguageProductionTargetCount).toBe(18);
    expect(result.safetyGateCount).toBe(1920);
    expect(result.workerCapabilityCardsAllowed).toBe(true);
    expect(result.workerFleetRegistryReadAllowed).toBe(true);
    expect(result.capabilityCardCatalogAllowed).toBe(true);
    expect(result.inputOutputContractAllowed).toBe(true);
    expect(result.ownerReviewCapabilityPacketAllowed).toBe(true);
    expect(result.workerExecutionAllowed).toBe(false);
    expect(result.workerSpawningAllowed).toBe(false);
    expect(result.autonomousDelegationAllowed).toBe(false);
    expect(result.projectRepoSourceMutated).toBe(false);
    expect(result.workerExecuted).toBe(false);
    expect(result.workerSpawned).toBe(false);
    expect(result.capabilityCardsPacketProduced).toBe(true);
    expect(result.capabilityCardManifestProduced).toBe(true);
    expect(result.workerCapabilityCardCatalogProduced).toBe(true);
    expect(result.ownerReviewManifestProduced).toBe(true);
    expect(result.readyForOwnerReview).toBe(true);
    expect(fs.existsSync(result.packetPath)).toBe(true);
    expect(fs.existsSync(result.capabilityCardManifestPath)).toBe(true);
    expect(fs.existsSync(result.workerCapabilityCardCatalogPath)).toBe(true);
    expect(fs.existsSync(result.ownerReviewManifestPath)).toBe(true);
  });

  it("requires Phase 101 lineage and Tyler approval", () => {
    const config = createDefaultWorkerCapabilityCardsV1();
    config.phase101WorkerFleetRegistryReady = false;
    config.sourceWorkerFleetRegistryId = "wrong-registry";
    config.approvalRecord.approved = false;
    config.approvalRecord.selfApproved = true;
    const result = inspectWorkerCapabilityCardsV1(config);
    expect(result.ok).toBe(false);
    expect(result.blockers).toContain("Phase 101 Worker Fleet Registry must be ready before Phase 102.");
    expect(result.blockers).toContain("Phase 102 must link to the Phase 101 Worker Fleet Registry.");
    expect(result.blockers).toContain("Tyler Wallace approval record is required for Phase 102 Worker Capability Cards.");
    expect(result.blockers).toContain("Self-approval is blocked for Phase 102 Worker Capability Cards.");
  });

  it("fails closed for unsafe or incomplete capability cards", () => {
    const config = createDefaultWorkerCapabilityCardsV1();
    config.workerCapabilityCards[0].cardId = "unsafe-card";
    config.workerCapabilityCards[0].workerId = "phase-planner";
    config.workerCapabilityCards[0].capabilityLevel = "execute";
    config.workerCapabilityCards[0].ownerReviewRequired = false;
    config.workerCapabilityCards[0].activationBoundary = "auto-run";
    config.workerCapabilityCards[0].hiddenPermissions = true;
    config.workerCapabilityCards[0].inputs = [];
    config.workerCapabilityCards[0].outputs = [];
    config.workerCapabilityCards[0].permissionBoundaries = [];
    config.workerCapabilityCards[0].evidenceRequirements = [];
    config.declaredPaths = ["../unsafe.txt"];
    const result = inspectWorkerCapabilityCardsV1(config);
    expect(result.ok).toBe(false);
    expect(result.blockers.some((blocker: string) => blocker.includes("safe relative path"))).toBe(true);
    expect(result.blockers.some((blocker: string) => blocker.includes("safe card.worker"))).toBe(true);
    expect(result.blockers.some((blocker: string) => blocker.includes("safe worker"))).toBe(true);
    expect(result.blockers.some((blocker: string) => blocker.includes("review-only"))).toBe(true);
    expect(result.blockers.some((blocker: string) => blocker.includes("owner review"))).toBe(true);
    expect(result.blockers.some((blocker: string) => blocker.includes("manual-owner-approval-only"))).toBe(true);
    expect(result.blockers.some((blocker: string) => blocker.includes("hidden worker permissions"))).toBe(true);
    expect(result.blockers.some((blocker: string) => blocker.includes("bounded inputs"))).toBe(true);
    expect(result.blockers.some((blocker: string) => blocker.includes("bounded outputs"))).toBe(true);
    expect(result.blockers.some((blocker: string) => blocker.includes("permission boundaries"))).toBe(true);
    expect(result.blockers.some((blocker: string) => blocker.includes("evidence requirements"))).toBe(true);
  });

  it("blocks unsafe worker, automation, project, Git, shell, fleet, and self-governance powers", () => {
    const config = createDefaultWorkerCapabilityCardsV1();
    config.boundaries.workerExecutionAllowed = true;
    config.boundaries.workerSpawningAllowed = true;
    config.boundaries.autonomousDelegationAllowed = true;
    config.boundaries.schedulerWorkflowMutationAllowed = true;
    config.boundaries.iPhoneAutomationMutationAllowed = true;
    config.boundaries.awayModeExecutionAllowed = true;
    config.boundaries.fleetExecutionAllowed = true;
    config.boundaries.applyExecutionAllowed = true;
    config.boundaries.patchExecutionAllowed = true;
    config.boundaries.projectRepoSourceMutationAllowed = true;
    config.boundaries.realProjectBranchCreationAllowed = true;
    config.boundaries.realProjectMergeExecutionAllowed = true;
    config.boundaries.gitPushAllowed = true;
    config.boundaries.tagCreationAllowed = true;
    config.boundaries.arbitraryCommandAllowed = true;
    config.boundaries.shellExecutionAllowed = true;
    config.boundaries.selfApprovalAllowed = true;
    config.boundaries.selfMergeAllowed = true;
    config.boundaries.selfDeployAllowed = true;
    config.boundaries.productionDeploymentAllowed = true;
    config.projectRepoSourceMutated = true;
    config.workerExecuted = true;
    config.workerSpawned = true;
    config.autonomousDelegationExecuted = true;
    config.schedulerWorkflowMutated = true;
    config.iPhoneAutomationMutated = true;
    config.awayModeExecuted = true;
    config.fleetExecuted = true;
    config.applyExecuted = true;
    config.patchExecuted = true;
    const result = inspectWorkerCapabilityCardsV1(config);
    expect(result.ok).toBe(false);
    expect(result.blockers).toContain("workerExecutionAllowed must remain false");
    expect(result.blockers).toContain("workerSpawningAllowed must remain false");
    expect(result.blockers).toContain("autonomousDelegationAllowed must remain false");
    expect(result.blockers).toContain("schedulerWorkflowMutationAllowed must remain false");
    expect(result.blockers).toContain("iPhoneAutomationMutationAllowed must remain false");
    expect(result.blockers).toContain("awayModeExecutionAllowed must remain false");
    expect(result.blockers).toContain("fleetExecutionAllowed must remain false");
    expect(result.blockers).toContain("applyExecutionAllowed must remain false");
    expect(result.blockers).toContain("patchExecutionAllowed must remain false");
    expect(result.blockers).toContain("projectRepoSourceMutationAllowed must remain false");
    expect(result.blockers).toContain("gitPushAllowed must remain false");
    expect(result.blockers).toContain("tagCreationAllowed must remain false");
    expect(result.blockers).toContain("shellExecutionAllowed must remain false");
    expect(result.blockers).toContain("selfApprovalAllowed must remain false");
    expect(result.blockers).toContain("productionDeploymentAllowed must remain false");
    expect(result.blockers).toContain("workerExecuted must remain false");
    expect(result.blockers).toContain("workerSpawned must remain false");
    expect(result.blockers).toContain("autonomousDelegationExecuted must remain false");
  });

  it("records validation failure evidence when capability card counts do not match expectations", () => {
    const artifactRoot = tempRoot("phase102-worker-capability-cards-failure");
    const config = createDefaultWorkerCapabilityCardsV1({ expectedWorkerCapabilityCardCount: 99 });
    const result = runWorkerCapabilityCardsV1(config, { artifactRoot });
    expect(result.ok).toBe(false);
    expect(result.validationFailedCount).toBe(1);
    expect(result.readyForOwnerReview).toBe(false);
    expect(result.projectRepoSourceMutated).toBe(false);
    expect(result.workerExecuted).toBe(false);
    expect(result.workerSpawned).toBe(false);
    const packet = JSON.parse(fs.readFileSync(result.packetPath, "utf8"));
    expect(packet.status).toBe("worker-capability-cards-validation-failed");
    expect(packet.ownerReviewManifest.readyForOwnerReview).toBe(false);
    expect(packet.checks.filter((check: { passed: boolean }) => !check.passed).length).toBe(1);
  });
});
