import http from "node:http";
import net from "node:net";
import { sha256 } from "./restricted-user-evidence";
type RequestApi = typeof http.request;
export async function observeOllama(input: { requestBytes: Buffer; endpoint?: string; request?: RequestApi }): Promise<{ normalized: any; requestBytes: Buffer; responseBytes: Buffer }> {
  const base=new URL(input.endpoint??"http://127.0.0.1:11434");if(base.hostname!=="127.0.0.1")throw new Error("OLLAMA_ENDPOINT_NOT_LITERAL_LOOPBACK");const requestedAt=new Date().toISOString(),request=input.request??http.request;
  const version=await call(request,base,"GET","/api/version",Buffer.alloc(0)),tags=await call(request,base,"GET","/api/tags",Buffer.alloc(0)),generation=await call(request,base,"POST","/api/generate",input.requestBytes);const versionBody=JSON.parse(version.bytes.toString("utf8")),tagsBody=JSON.parse(tags.bytes.toString("utf8")),response=JSON.parse(generation.bytes.toString("utf8")),model=(tagsBody.models??[]).find((m:any)=>m.name==="llama3.2:1b"||m.model==="llama3.2:1b");if(!model||response.model!=="llama3.2:1b")throw new Error("OLLAMA_MODEL_IDENTITY_MISMATCH");
  return{requestBytes:input.requestBytes,responseBytes:generation.bytes,normalized:{endpointHost:base.hostname,socketRemoteAddress:generation.remote,providerId:"ollama-loopback-base-mvp-v1",providerVersion:versionBody.version,model:"llama3.2:1b",observedModel:response.model,modelDigest:model.digest,requestSha256:sha256(input.requestBytes),responseSha256:sha256(generation.bytes),requestedAt,respondedAt:new Date().toISOString(),candidateOnly:true,authorities:[]}};
}
function call(request:RequestApi,base:URL,method:string,pathname:string,bytes:Buffer):Promise<{bytes:Buffer;remote:string}>{return new Promise((resolve,reject)=>{const req=request({hostname:base.hostname,port:Number(base.port||80),path:pathname,method,timeout:10_000,headers:bytes.length?{"content-type":"application/json","content-length":bytes.length}:{}},res=>{const chunks:Buffer[]=[];res.on("data",c=>chunks.push(Buffer.from(c)));res.on("end",()=>{const remote=normalizeRemote(res.socket.remoteAddress??"");if(!remote)return reject(new Error("OLLAMA_REMOTE_NOT_LOOPBACK"));if((res.statusCode??500)>=400)return reject(new Error(`OLLAMA_HTTP_${res.statusCode}`));resolve({bytes:Buffer.concat(chunks),remote});});});req.on("timeout",()=>req.destroy(new Error("OLLAMA_TIMEOUT")));req.on("error",reject);if(bytes.length)req.write(bytes);req.end();});}
function normalizeRemote(remote:string):string|null{if(!net.isIP(remote))return null;if(remote==="::ffff:127.0.0.1")return"127.0.0.1";return remote==="127.0.0.1"||remote==="::1"?remote:null;}
