import fs from "node:fs";
import path from "node:path";
import { sha256File } from "./restricted-user-evidence";
const tools=/^(git|npm|npx|codex|code|devenv|cl|msbuild|winget|choco)(\.exe|\.cmd)?$/i;
export interface LiveBindingAuditInput { releaseRoot:string; repositoryRoot:string; releaseManifest:any; preparation:any; evidenceManifest:any; provenance:any; monitor:any; workflowStart:any; workflowComplete:any; runtimePath:string; collectorPath:string; monitorPath:string; proofSid:string; }
export function auditLiveBinding(i:LiveBindingAuditInput):string[]{const r:string[]=[];const fail=(c:string,p:boolean)=>{if(!p&&!r.includes(c))r.push(c)};const inside=(f:string,root:string)=>{try{return fs.realpathSync(f).startsWith(`${fs.realpathSync(root)}${path.sep}`)}catch{return false}},digest=(f:string)=>{try{return sha256File(f)}catch{return""}},entry=(p:string)=>i.releaseManifest.files?.find((x:any)=>x.path===p),prepared=(p:string)=>i.preparation.collectors?.find((x:any)=>x.relativePath===p);
fail("PRODUCTION_MONITOR_INJECTED",i.monitor.liveSubscription===true&&i.monitor.sourceEventType==="Win32_ProcessStartTrace");fail("LIVE_SUBSCRIPTION_HANDSHAKE_MISSING",i.monitor.readyHandshake===true);fail("MONITOR_STARTED_TOO_LATE",Date.parse(i.monitor.startedAt)<Date.parse(i.workflowStart.workflowStartedAt));fail("MONITOR_STOPPED_TOO_EARLY",Date.parse(i.monitor.stoppedAt)>Date.parse(i.workflowComplete.workflowCompletedAt));fail("MONITOR_INTERRUPTED",i.monitor.completeness==="COMPLETE");fail("EVENT_FLUSH_INCOMPLETE",i.monitor.flushed!==false);fail("MONITOR_SESSION_MISMATCH",i.monitor.sessionId===i.evidenceManifest.sessionId);fail("MONITOR_NONCE_MISMATCH",i.monitor.nonce===i.evidenceManifest.nonce);fail("MONITOR_PROOF_SID_MISMATCH",i.monitor.proofSid===i.proofSid);
const events=i.monitor.events??[];fail("PROHIBITED_GIT_PROCESS",!events.some((e:any)=>/^git\.exe$/i.test(e.executableName)));fail("PROHIBITED_NPM_PROCESS",!events.some((e:any)=>/^n(pm|px)(\.cmd)?$/i.test(e.executableName)));fail("PROHIBITED_DEVELOPMENT_TOOL",!events.some((e:any)=>tools.test(e.executableName)&&!/^git\.exe$|^n(pm|px)/i.test(e.executableName)));const wrongNode=events.some((e:any)=>/^node\.exe$/i.test(e.executableName)&&(path.resolve(e.executablePath??"").toLowerCase()!==path.resolve(i.runtimePath).toLowerCase()||e.executableSha256&&e.executableSha256!==digest(i.runtimePath)));fail("SYSTEM_NODE_OBSERVED",!wrongNode);
fail("COLLECTOR_EXECUTED_FROM_REPOSITORY",!inside(i.collectorPath,i.repositoryRoot));fail("COLLECTOR_OUTSIDE_RELEASE",inside(i.collectorPath,i.releaseRoot));fail("RUNTIME_OUTSIDE_RELEASE",inside(i.runtimePath,i.releaseRoot));fail("PROCESS_MONITOR_OUTSIDE_RELEASE",inside(i.monitorPath,i.releaseRoot));const collectorRel="collectors/restricted-user-collector.cjs",monitorRel="collectors/process-start-monitor.ps1";fail("COLLECTOR_DIGEST_ALTERED",digest(i.collectorPath)===entry(collectorRel)?.sha256&&digest(i.collectorPath)===prepared(collectorRel)?.sha256&&digest(i.collectorPath)===i.provenance.collectorSha256);fail("PROCESS_MONITOR_DIGEST_ALTERED",digest(i.monitorPath)===entry(monitorRel)?.sha256&&digest(i.monitorPath)===prepared(monitorRel)?.sha256&&digest(i.monitorPath)===i.provenance.monitorSha256);fail("RUNTIME_COLLECTOR_RELEASE_MISMATCH",path.dirname(path.dirname(i.runtimePath))===i.releaseRoot&&path.dirname(path.dirname(i.collectorPath))===i.releaseRoot);fail("RELEASE_MANIFEST_OMITS_COLLECTOR",!!entry(collectorRel)&&!!entry(monitorRel));fail("PREPARATION_COLLECTOR_MISMATCH",!!prepared(collectorRel)&&!!prepared(monitorRel));fail("EVIDENCE_BEFORE_PREPARATION",Date.parse(i.provenance.startedAt)>=Date.parse(i.preparation.preparedAt));fail("COLLECTOR_PROCESS_IDENTITY_MISMATCH",i.provenance.collectorPid===i.provenance.runtimePid&&i.provenance.collectorPid>0);fail("COLLECTOR_REPARSE_ESCAPE",inside(i.collectorPath,i.releaseRoot)&&inside(i.monitorPath,i.releaseRoot));fail("DEVELOPMENT_SMOKE_PROMOTION_ATTEMPT",i.provenance.invocation==="REAL_RESTRICTED_USER_PROOF");fail("REPOSITORY_DIRECT_PROMOTABLE_COLLECTION",i.provenance.repositoryDelegation!==true||i.provenance.invocation!=="REAL_RESTRICTED_USER_PROOF");return r.sort();}
