import fs from "node:fs";
import path from "node:path";
import { runWindowsCommand, WINDOWS_TOOLS } from "./restricted-user-command-runner";
import { safeArtifactPath, sha256File } from "./restricted-user-evidence";
import { encodePowerShell } from "./restricted-user-network";
export const VISUAL_STAGES = ["packaged-launcher", "desktop-operator-loaded", "runtime-health", "supported-intake", "provenance", "model-candidate", "evaluation", "operator-review", "digest-bound-approval", "closeout", "evidence-history"] as const;
export function captureVisual(input: { root: string; stage: string; proofSid: string; sessionId: string; nonce: string; releaseIdentity: string; activeProcess?: string; imageSource?: () => Buffer; run?: typeof runWindowsCommand }): any {
  if (!(VISUAL_STAGES as readonly string[]).includes(input.stage)) throw new Error("UNKNOWN_VISUAL_STAGE"); const relative = `visual/${input.stage}.png`, full = safeArtifactPath(input.root, relative); if (!full) throw new Error("UNSAFE_VISUAL_PATH"); if (fs.existsSync(full)) throw new Error("DUPLICATE_VISUAL_STAGE"); fs.mkdirSync(path.dirname(full), { recursive: true });
  if (input.imageSource) fs.writeFileSync(full, input.imageSource()); else { const script = "Add-Type -AssemblyName System.Windows.Forms;Add-Type -AssemblyName System.Drawing;$p=[Environment]::GetEnvironmentVariable('SERA_CAPTURE_PATH');$b=[System.Windows.Forms.Screen]::PrimaryScreen.Bounds;$i=New-Object System.Drawing.Bitmap $b.Width,$b.Height;$g=[System.Drawing.Graphics]::FromImage($i);$g.CopyFromScreen($b.Location,[System.Drawing.Point]::Empty,$b.Size);$i.Save($p,[System.Drawing.Imaging.ImageFormat]::Png);$g.Dispose();$i.Dispose()"; const run = input.run ?? runWindowsCommand, observed = run(WINDOWS_TOOLS.powershell, ["-NoProfile", "-NonInteractive", "-EncodedCommand", encodePowerShell(script)], { timeoutMs: 15_000, env: { SystemRoot: process.env.SystemRoot, WINDIR: process.env.WINDIR, SERA_CAPTURE_PATH: full } }); if (observed.failure !== "NONE") throw new Error("VISUAL_CAPTURE_FAILED"); }
  if (!fs.existsSync(full) || fs.statSync(full).size === 0) throw new Error("VISUAL_CAPTURE_EMPTY"); return { stage: input.stage, imagePath: relative, sha256: sha256File(full), size: fs.statSync(full).size, capturedAt: new Date().toISOString(), proofSid: input.proofSid, sessionId: input.sessionId, nonce: input.nonce, releaseIdentity: input.releaseIdentity, activeProcess: input.activeProcess ?? null, semanticInterpretation: false };
}
