import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";
import { spawnSync } from "node:child_process";
import { collectAccountObservation } from "./restricted-user-account";
import { normalizedTreeDigest, sha256, sha256File } from "./restricted-user-evidence";
import { collectDenialObservations, type DenialTarget } from "./restricted-user-filesystem";
import { collectReleaseObservation } from "./restricted-user-release";
import { buildSanitizedEnvironment, observeRedactedEnvironment } from "./restricted-user-environment";
import { ProofProcessMonitor } from "./restricted-user-process-monitor";
import { observeOllama } from "./restricted-user-provider";
import { collectAdapterInventory, collectConnectivity } from "./restricted-user-network";
import { collectBootObservation, compareBootObservations } from "./restricted-user-restart";
import { captureVisual, VISUAL_STAGES } from "./restricted-user-visual";
import { finalizeEvidenceManifest, writeEvidenceArtifact } from "./restricted-user-writer";

export class RestrictedCollectionBlockedError extends Error { constructor(readonly code: string, message: string) { super(message); } }
export function createPreparationManifest(input: { projectRoot: string; outputRoot: string; releaseZip: string; extractionRoot: string; releaseManifest: string; collectorFiles: string[]; proofAccountName: string; proofSid: string; developmentSid: string; hostProfileId: string; governanceDecision: string; observerRoot:string; developmentStatePaths?: string[]; networkRestorationState?: unknown }): Record<string, unknown> {
  const projectRoot=fs.realpathSync(path.resolve(input.projectRoot)),gitPath=path.join(projectRoot,".git"),extractionRoot=fs.realpathSync(path.resolve(input.extractionRoot)),releaseManifest=JSON.parse(fs.readFileSync(input.releaseManifest,"utf8")),runtimePath=fs.realpathSync(path.join(extractionRoot,...String(releaseManifest.runtime.path).split("/"))),collectorFiles=[...new Set([...(input.collectorFiles??[]),path.join(extractionRoot,"collectors","restricted-user-collector.cjs"),path.join(extractionRoot,"collectors","privileged-observer.cjs"),path.join(extractionRoot,"collectors","process-start-monitor.ps1")])];
  const collectors=collectorFiles.map(file=>{const resolved=fs.realpathSync(path.resolve(file));if(!resolved.startsWith(`${extractionRoot}${path.sep}`))throw new RestrictedCollectionBlockedError("RELEASE_CONTAINED_COLLECTOR_REQUIRED","Prepared collector must be inside the release.");const relativePath=path.relative(extractionRoot,resolved).replace(/\\/g,"/"),record=releaseManifest.files.find((f:any)=>f.path===relativePath);if(!record||record.sha256!==sha256File(resolved))throw new RestrictedCollectionBlockedError("RELEASE_MANIFEST_COLLECTOR_MISMATCH",relativePath);return{path:resolved,relativePath,size:fs.statSync(resolved).size,sha256:sha256File(resolved)};}).sort((a,b)=>a.relativePath.localeCompare(b.relativePath));
  const manifest={schemaVersion:"sera.restricted-user-preparation-manifest.v5.2",profileId:"same-host-restricted-user-release-only-v1",observerProfile:"privileged-observer-sidecar-v1",evidenceMode:"governed-windows-v2",observerRoot:path.resolve(input.observerRoot),sessionId:crypto.randomUUID(),nonce:crypto.randomBytes(32).toString("hex"),preparedAt:new Date().toISOString(),hostProfileId:input.hostProfileId,developmentSid:input.developmentSid,expectedProofSid:input.proofSid,expectedProofAccountName:input.proofAccountName,repository:{canonicalPath:projectRoot,identity:fs.statSync(projectRoot).birthtimeMs,gitPath,gitIdentity:fs.existsSync(gitPath)?fs.statSync(gitPath).birthtimeMs:null},developmentStatePaths:(input.developmentStatePaths??[]).map(p=>path.resolve(p)),release:{zipPath:path.resolve(input.releaseZip),zipSha256:sha256File(input.releaseZip),expectedExtractionRoot:extractionRoot,extractedTreeDigest:normalizedTreeDigest(extractionRoot),releaseManifestPath:path.resolve(input.releaseManifest),releaseManifestDigest:sha256File(input.releaseManifest),runtimePath,runtimeRelativePath:releaseManifest.runtime.path,runtimeSize:fs.statSync(runtimePath).size,runtimeSha256:sha256File(runtimePath)},collectors,provider:{id:"ollama-loopback-base-mvp-v1",model:"llama3.2:1b"},networkRestorationState:input.networkRestorationState??[],governanceDecisionPath:path.resolve(input.governanceDecision),governanceDecisionDigest:sha256File(input.governanceDecision),restrictedUserObservationsOccurred:false};fs.mkdirSync(path.resolve(input.outputRoot),{recursive:true});const target=path.join(path.resolve(input.outputRoot),"preparation-manifest.json");fs.writeFileSync(target,`${JSON.stringify(manifest,null,2)}\n`,{flag:"wx"});return{ok:true,status:"PREPARATION_MANIFEST_WRITTEN",path:target,sessionId:manifest.sessionId};
}
export async function collectPreRestart(preparationPath: string): Promise<any> {
  requireWindows(); const prep=readPreparation(preparationPath),root=path.dirname(path.resolve(preparationPath)); let account:any;
  try { account=collectAccountObservation({expectedSid:prep.expectedProofSid,developmentSid:prep.developmentSid,expectedAccount:prep.expectedProofAccountName,profileCreatedAt:fs.statSync(process.env.USERPROFILE!).birthtime.toISOString()}); } catch(error){ throw new RestrictedCollectionBlockedError((error as Error).message,"Pre-restart collection refused by account/token boundary."); }
  const rawRoot="raw/account";for(const [name,value] of Object.entries(account.raw))writeEvidenceArtifact(root,`${rawRoot}/${name}.json`,value);writeEvidenceArtifact(root,"pre/account-token.json",account.normalized);
  const targets:DenialTarget[]=[{targetRole:"repository-root",requestedPath:prep.repository.canonicalPath},{targetRole:"repository-git",requestedPath:prep.repository.gitPath,knownChild:"HEAD"},{targetRole:"repository-node-modules",requestedPath:path.join(prep.repository.canonicalPath,"node_modules")},{targetRole:"repository-sera",requestedPath:path.join(prep.repository.canonicalPath,".sera")},{targetRole:"development-codex",requestedPath:path.join(path.dirname(prep.repository.canonicalPath),".codex")},{targetRole:"sera-sandbox",requestedPath:"C:\\SERA-SANDBOX"},{targetRole:"dev-root",requestedPath:"C:\\dev"},...(prep.developmentStatePaths??[]).map((p:string,i:number)=>({targetRole:i===0?"development-sqlite":"configured-private-root",requestedPath:p}))];writeEvidenceArtifact(root,"pre/source-denial.json",{observations:collectDenialObservations(targets,account.normalized.proofSid)});
  const release=collectReleaseObservation({preparation:prep,proofSid:account.normalized.proofSid,sessionId:prep.sessionId});writeEvidenceArtifact(root,"pre/release-runtime.json",release);const monitor=new ProofProcessMonitor(prep.sessionId,prep.nonce,account.normalized.proofSid);monitor.record({timestamp:release.startedAt,pid:release.pid,parentPid:release.parentPid,executableName:path.basename(release.execPath),executablePath:release.execPath,proofSid:account.normalized.proofSid});writeEvidenceArtifact(root,"pre/process-events.json",monitor.stop());
  const env=buildSanitizedEnvironment(process.env,path.dirname(release.runtimePath));writeEvidenceArtifact(root,"pre/environment.json",observeRedactedEnvironment(env,release.pid,prep.sessionId,[prep.repository.canonicalPath,...(prep.developmentStatePaths??[])]));
  const requestBytes=Buffer.from(JSON.stringify({model:"llama3.2:1b",prompt:"Return a bounded candidate-only proof observation.",stream:false}));const provider=await observeOllama({requestBytes});writeEvidenceArtifact(root,"pre/ollama-request.bin",provider.requestBytes);writeEvidenceArtifact(root,"pre/ollama-response.bin",provider.responseBytes);provider.normalized.requestArtifact="pre/ollama-request.bin";provider.normalized.responseArtifact="pre/ollama-response.bin";writeEvidenceArtifact(root,"pre/ollama.json",provider.normalized);
  const network={...collectAdapterInventory(),...await collectConnectivity()};if(network.adapters.some((a:any)=>a.publicRouteCapable&&a.administrativeStatus!=="disabled"))throw new RestrictedCollectionBlockedError("PUBLIC_ADAPTER_ENABLED","A public-route-capable adapter remains enabled.");if([network.publicDns,network.publicIpv4Tcp,network.publicHttp,network.publicHttps].some(v=>v==="SUCCEEDED"))throw new RestrictedCollectionBlockedError("PUBLIC_ENDPOINT_REACHABLE","Public connectivity remains reachable.");writeEvidenceArtifact(root,"pre/network.json",network);writeEvidenceArtifact(root,"pre/boot.json",collectBootObservation({hostProfileId:prep.hostProfileId,installationId:readInstallationId(prep.installationIdentityRecord?.path,prep),sessionId:prep.sessionId,nonce:prep.nonce,processId:release.pid}));
  if(!fs.existsSync(path.join(root,"governance-decision.json")))fs.copyFileSync(prep.governanceDecisionPath,path.join(root,"governance-decision.json"));return{ok:true,status:"PRE_RESTART_OBSERVED",evidenceRoot:root,sessionId:prep.sessionId,modelUse:true,publicNetworkUse:false};
}
export function captureStage(stage:string,preparationPath:string,imageSource?:()=>Buffer):any{requireWindowsUnlessInjected(imageSource);const prep=readPreparation(preparationPath),root=path.dirname(path.resolve(preparationPath)),account=collectAccountObservation({expectedSid:prep.expectedProofSid,developmentSid:prep.developmentSid,expectedAccount:prep.expectedProofAccountName});const release=JSON.parse(fs.readFileSync(path.join(root,"pre/release-runtime.json"),"utf8")),metadata=captureVisual({root,stage,proofSid:account.normalized.proofSid,sessionId:prep.sessionId,nonce:prep.nonce,releaseIdentity:release.releaseIdentity,activeProcess:release.execPath,imageSource});const desktopPath=path.join(root,"pre","desktop.json"),desktop=fs.existsSync(desktopPath)?JSON.parse(fs.readFileSync(desktopPath,"utf8")):{stages:[]};desktop.stages.push(metadata);fs.mkdirSync(path.dirname(desktopPath),{recursive:true});fs.writeFileSync(desktopPath,`${JSON.stringify(desktop,null,2)}\n`,{flag:fs.existsSync(desktopPath)?"w":"wx"});return{ok:true,status:"VISUAL_CAPTURED",...metadata};}
export function collectPostRestart(preparationPath:string):any{
 requireWindows();const prep=readPreparation(preparationPath),root=path.dirname(path.resolve(preparationPath)),before=JSON.parse(fs.readFileSync(path.join(root,"pre","boot.json"),"utf8")),release=JSON.parse(fs.readFileSync(path.join(root,"pre","release-runtime.json"),"utf8")),after=collectBootObservation({hostProfileId:prep.hostProfileId,installationId:before.installationId,sessionId:prep.sessionId,nonce:prep.nonce,processId:process.pid});let restart;
 try{restart=compareBootObservations(before,after)}catch{throw new RestrictedCollectionBlockedError("WINDOWS_BOOT_IDENTITY_UNCHANGED","Post-restart collection requires a verified Windows boot change.")}
 for(const file of ["post/persistence.json","post/recurrence.json","negative-cases.json","pre/persistence.json","pre/desktop.json"])if(!fs.existsSync(path.join(root,...file.split("/"))))throw new RestrictedCollectionBlockedError("POST_RESTART_APPLICATION_EVIDENCE_MISSING",`${file} is required.`);
 writeEvidenceArtifact(root,"post/restart.json",restart);const collector=prep.subjectCollector??prep.collectors?.find((x:any)=>x.relativePath==="collectors/restricted-user-collector.cjs");if(!collector)throw new RestrictedCollectionBlockedError("COLLECTOR_IDENTITY_MISSING","Prepared collector identity is required.");
 const manifest=finalizeEvidenceManifest({root,profileId:prep.profileId,evidenceMode:"governed-windows-v2",sessionId:prep.sessionId,nonce:prep.nonce,proofSid:prep.expectedProofSid,collectorId:"sera-windows-collector/v4",collectorSha256:collector.sha256,installationIdentity:prep.installationIdentity,installationIdentityRecordDigest:prep.installationIdentityRecord?.sha256,subjectCollectorDigest:prep.subjectCollector?.sha256,preparationManifestDigest:sha256File(path.join(root,"preparation-manifest.json")),governanceDecisionDigest:sha256File(path.join(root,"governance-decision.json")),stageFor:p=>p.startsWith("post/")||p.startsWith("observer/post-")?"post-restart":p.startsWith("pre/")||p.startsWith("raw/")||p.startsWith("visual/")||p.startsWith("observer/pre-")?"pre-restart":"preparation"});return{ok:true,status:"POST_RESTART_OBSERVED",evidenceRoot:root,previousPid:release.pid,currentPid:process.pid,manifestDigest:manifest.manifestDigest};
}
function readPreparation(file:string):any{if(!fs.existsSync(path.resolve(file)))throw new RestrictedCollectionBlockedError("PREPARATION_MANIFEST_MISSING","Preparation manifest is required.");return JSON.parse(fs.readFileSync(path.resolve(file),"utf8"));}function readInstallationId(fileInput:string,prep:any):string{const file=path.resolve(String(fileInput??""));if(!fs.existsSync(file))throw new RestrictedCollectionBlockedError("INSTALLATION_IDENTITY_MISSING","Governed installation identity is required.");const record=JSON.parse(fs.readFileSync(file,"utf8"));if(record.installationId!==prep.installationIdentity||record.proofSessionId!==prep.sessionId||record.nonce!==prep.nonce||record.hostProfileId!==prep.hostProfileId||record.releaseManifestDigest!==prep.release.releaseManifestDigest||record.extractedTreeDigest!==prep.release.extractedTreeDigest)throw new RestrictedCollectionBlockedError("INSTALLATION_RELEASE_BINDING_MISMATCH","Installation identity binding changed.");return record.installationId;}function requireWindows():void{if(process.platform!=="win32")throw new RestrictedCollectionBlockedError("WINDOWS_REQUIRED","Collector requires Windows.");}function requireWindowsUnlessInjected(source?:()=>Buffer):void{if(!source)requireWindows();}
export { VISUAL_STAGES };
export function invokePackagedCollector(preparationPath:string,action:string,args:string[]=[]):any{const prep=readPreparation(preparationPath),mode=prep.invocationMode;if(!["NON_PROMOTABLE_DEVELOPMENT_SMOKE","NON_PROMOTABLE_PRODUCTION_ROUNDTRIP_TEST","REAL_RESTRICTED_USER_PROOF"].includes(mode))throw new RestrictedCollectionBlockedError("PREPARATION_INVOCATION_MODE_REQUIRED","Preparation must govern invocation mode.");const root=fs.realpathSync(prep.release.expectedExtractionRoot),runtime=fs.realpathSync(prep.release.runtimePath??path.join(root,"runtime","node.exe")),collector=fs.realpathSync(path.join(root,"collectors","restricted-user-collector.cjs"));if(!runtime.startsWith(`${root}${path.sep}`)||!collector.startsWith(`${root}${path.sep}`))throw new RestrictedCollectionBlockedError("RELEASE_CONTAINED_COLLECTOR_REQUIRED","Packaged runtime and collector are required.");const result=spawnSync(runtime,[collector,action,...args],{shell:false,encoding:"utf8",timeout:30_000,windowsHide:true,cwd:root,env:{SystemRoot:process.env.SystemRoot,WINDIR:process.env.WINDIR,TEMP:process.env.TEMP,TMP:process.env.TMP,PATH:path.dirname(runtime),SERA_PROOF_INVOCATION:mode}});let output:any;const lines=`${String(result.stdout)}\n${String(result.stderr)}`.split(/\r?\n/).map(x=>x.trim()).filter(x=>x.startsWith("{")).reverse();try{if(!lines.length)throw new Error("missing JSON");output=JSON.parse(lines[0]);}catch{output={ok:false,status:"BLOCKED",reasonCode:"PACKAGED_COLLECTOR_OUTPUT_INVALID",exitCode:result.status};}return{...output,repositoryDelegation:true,invocation:mode,claimsGranted:[]};}
