import dns from "node:dns/promises";
import net from "node:net";
import { runWindowsCommand, WINDOWS_TOOLS } from "./restricted-user-command-runner";
export function encodePowerShell(script: string): string { return Buffer.from(script, "utf16le").toString("base64"); }
export function collectAdapterInventory(run = runWindowsCommand): any {
  const script = "$a=Get-NetAdapter -IncludeHidden | ForEach-Object {$i=Get-NetIPInterface -InterfaceIndex $_.ifIndex -ErrorAction SilentlyContinue;[pscustomobject]@{interfaceGuid=$_.InterfaceGuid.Guid;interfaceIndex=$_.ifIndex;name=$_.Name;description=$_.InterfaceDescription;type=if($_.Name -match 'Loopback'){'loopback'}elseif($_.NdisPhysicalMedium -eq 9){'wifi'}elseif($_.Virtual){'tunnel'}else{'ethernet'};operationalStatus=$_.Status.ToString().ToLower();administrativeStatus=if($_.AdminStatus -eq 'Up'){'enabled'}else{'disabled'};ipv4State=($i|? AddressFamily -eq IPv4|select -First 1).ConnectionState;ipv6State=($i|? AddressFamily -eq IPv6|select -First 1).ConnectionState}};$r=Get-NetRoute|select InterfaceIndex,DestinationPrefix,NextHop,RouteMetric;$o=[pscustomobject]@{adapters=$a;routes=$r};$o|ConvertTo-Json -Depth 5 -Compress";
  const observed = run(WINDOWS_TOOLS.powershell, ["-NoProfile", "-NonInteractive", "-EncodedCommand", encodePowerShell(script)], { timeoutMs: 15_000 }); if (observed.failure !== "NONE") throw new Error("ADAPTER_INVENTORY_FAILED");
  const value = JSON.parse(observed.stdout), routes = Array.isArray(value.routes) ? value.routes : value.routes ? [value.routes] : [], adapters = (Array.isArray(value.adapters) ? value.adapters : [value.adapters]).map((a: any) => ({ ...a, publicRouteCapable: routes.some((r: any) => r.InterfaceIndex === a.interfaceIndex && ["0.0.0.0/0", "::/0"].includes(r.DestinationPrefix)), inRestorationManifest: a.type !== "loopback" }));
  return { inventoryComplete: true, adapters, routes };
}
export async function tcpProbe(host: string, port: number, timeoutMs = 1500): Promise<"SUCCEEDED" | "FAILED"> { return new Promise((resolve) => { const socket = net.connect({ host, port }); const done = (v: "SUCCEEDED"|"FAILED") => { socket.destroy(); resolve(v); }; socket.setTimeout(timeoutMs, () => done("FAILED")); socket.once("connect", () => done("SUCCEEDED")); socket.once("error", () => done("FAILED")); }); }
export async function collectConnectivity(): Promise<any> { let publicDns: "SUCCEEDED"|"FAILED"="FAILED"; try { await dns.resolve4("example.com"); publicDns="SUCCEEDED"; } catch {} const ollama=await tcpProbe("127.0.0.1",11434),desktopOperator=await tcpProbe("127.0.0.1",4317);return { publicDns, publicIpv4Tcp: await tcpProbe("1.1.1.1",443), publicIpv6: await tcpProbe("2606:4700:4700::1111",443), publicHttp: await tcpProbe("93.184.216.34",80), publicHttps: await tcpProbe("93.184.216.34",443), localhost:ollama==="SUCCEEDED"||desktopOperator==="SUCCEEDED"?"SUCCEEDED":"FAILED", ollama, desktopOperator }; }
