import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import { normalizedTreeDigest, sha256, sha256File } from "./restricted-user-evidence";
import { finalizeEvidenceManifest,writeEvidenceArtifact } from "./restricted-user-writer";
import type { BootStageName } from "./restricted-user-identity-binding";

export const INSTALLATION_IDENTITY_SCHEMA="sera.restricted-user-installation-identity.v1";
export const COLLECTOR_IDENTITY_SCHEMA="sera.restricted-user-subject-collector-identity.v1";
export const BOOT_STAGE_SCHEMA="sera.restricted-user-boot-stage.v1";
export const RESTRICTED_INVOCATION_MODES=["NON_PROMOTABLE_DEVELOPMENT_SMOKE","NON_PROMOTABLE_PRODUCTION_ROUNDTRIP_TEST","REAL_RESTRICTED_USER_PROOF"] as const;
export type RestrictedInvocationMode=typeof RESTRICTED_INVOCATION_MODES[number];
const collectorRelative="collectors/restricted-user-collector.cjs";
const portable=(root:string,file:string)=>path.relative(root,file).replace(/\\/g,"/");
const read=(file:string)=>JSON.parse(fs.readFileSync(file,"utf8"));

export function prepareProductionIdentityBindings(preparationPath:string,options:{uuid?:()=>string;now?:()=>string;invocationMode?:RestrictedInvocationMode;roundTripAdapters?:any}={}):any{
 const file=path.resolve(preparationPath),prep=read(file),evidenceRoot=path.dirname(file),releaseRoot=fs.realpathSync(prep.release.expectedExtractionRoot),repositoryRoot=fs.realpathSync(prep.repository.canonicalPath),stateRoot=path.join(evidenceRoot,"State");
 if(stateRoot.toLowerCase().startsWith(`${repositoryRoot.toLowerCase()}${path.sep}`)||stateRoot.toLowerCase().startsWith(`${releaseRoot.toLowerCase()}${path.sep}`))throw new Error("INSTALLATION_STATE_BOUNDARY_INVALID");
 if((options.invocationMode??prep.invocationMode)==="NON_PROMOTABLE_PRODUCTION_ROUNDTRIP_TEST")prep.roundTripAdapters=options.roundTripAdapters??prep.roundTripAdapters;
 fs.mkdirSync(stateRoot,{recursive:true});const identityPath=path.join(stateRoot,"installation-identity.json"),releaseManifest=read(prep.release.releaseManifestPath),releaseIdentity=String(releaseManifest.version??releaseManifest.releaseIdentity??prep.release.releaseManifestDigest),now=options.now??(()=>new Date().toISOString());
 let identity:any;if(fs.existsSync(identityPath)){identity=read(identityPath);if(identity.schemaVersion!==INSTALLATION_IDENTITY_SCHEMA||!identity.installationId)throw new Error("INSTALLATION_IDENTITY_MALFORMED");}
 else{identity={schemaVersion:INSTALLATION_IDENTITY_SCHEMA,installationId:(options.uuid??crypto.randomUUID)(),createdAt:now(),hostProfileId:prep.hostProfileId,proofSessionId:prep.sessionId,nonce:prep.nonce,releaseZipDigest:prep.release.zipSha256,releaseManifestDigest:prep.release.releaseManifestDigest,extractedTreeDigest:prep.release.extractedTreeDigest,releaseIdentity,installationStateRelativePath:"State/installation-identity.json"};fs.writeFileSync(identityPath,`${JSON.stringify(identity,null,2)}\n`,{flag:"wx"});}
 for(const [k,v] of Object.entries({hostProfileId:prep.hostProfileId,proofSessionId:prep.sessionId,nonce:prep.nonce,releaseManifestDigest:prep.release.releaseManifestDigest,extractedTreeDigest:prep.release.extractedTreeDigest,releaseIdentity}))if(identity[k]!==v)throw new Error("INSTALLATION_RELEASE_BINDING_MISMATCH");
 const collectorPath=fs.realpathSync(path.join(releaseRoot,...collectorRelative.split("/"))),runtimePath=fs.realpathSync(prep.release.runtimePath),entry=releaseManifest.files?.find((x:any)=>x.path===collectorRelative);if(!entry||entry.sha256!==sha256File(collectorPath)||entry.size!==fs.statSync(collectorPath).size)throw new Error("SUBJECT_COLLECTOR_RELEASE_MISMATCH");
 prep.schemaVersion="sera.restricted-user-preparation-manifest.v5.5";prep.identityBindingSchema="sera.restricted-user-identity-bindings.v5.3";prep.invocationMode=options.invocationMode??prep.invocationMode??"NON_PROMOTABLE_DEVELOPMENT_SMOKE";if(!RESTRICTED_INVOCATION_MODES.includes(prep.invocationMode))throw new Error("PREPARATION_INVOCATION_MODE_REQUIRED");prep.installationIdentity=identity.installationId;prep.installationIdentityRecord={path:identityPath,relativePath:"State/installation-identity.json",sha256:sha256File(identityPath),size:fs.statSync(identityPath).size};prep.installationBinding={releaseIdentity,releaseManifestDigest:prep.release.releaseManifestDigest,extractedTreeDigest:prep.release.extractedTreeDigest,hostProfileId:prep.hostProfileId,proofSessionId:prep.sessionId,nonce:prep.nonce};prep.subjectCollector={relativePath:collectorRelative,canonicalPath:collectorPath,size:entry.size,sha256:entry.sha256,releaseManifestEntry:entry,runtimePath,runtimeSize:fs.statSync(runtimePath).size,runtimeSha256:sha256File(runtimePath)};prep.expectedStages=["PRE_RESTART","POST_RESTART"];prep.bootObservationSchemaVersion=BOOT_STAGE_SCHEMA;prep.evidenceRoots={subject:{canonicalPath:evidenceRoot,identity:sha256(path.resolve(evidenceRoot).toLowerCase())},observer:{canonicalPath:path.resolve(prep.observerRoot),identity:sha256(path.resolve(prep.observerRoot).toLowerCase())}};fs.writeFileSync(file,`${JSON.stringify(prep,null,2)}\n`);return prep;
}

export function readVerifiedInstallationIdentity(prep:any):any{const file=prep.installationIdentityRecord?.path??"",record=read(file),stat=fs.statSync(file);if(record.schemaVersion!==INSTALLATION_IDENTITY_SCHEMA||record.installationId!==prep.installationIdentity||stat.size!==prep.installationIdentityRecord.size||sha256File(file)!==prep.installationIdentityRecord.sha256)throw new Error("INSTALLATION_IDENTITY_MALFORMED");return record}
export function buildSubjectCollectorIdentity(prep:any,stage:BootStageName,processIdentity:any={}):any{const c=prep.subjectCollector,actual=fs.realpathSync(c.canonicalPath),runtime=fs.realpathSync(processIdentity.runtimePath??c.runtimePath);if(sha256File(actual)!==c.sha256||fs.statSync(actual).size!==c.size)throw new Error("SUBJECT_COLLECTOR_DIGEST_MISMATCH");if(sha256File(runtime)!==c.runtimeSha256||fs.statSync(runtime).size!==c.runtimeSize)throw new Error("SUBJECT_COLLECTOR_PROCESS_PROVENANCE_MISMATCH");return{schemaVersion:COLLECTOR_IDENTITY_SCHEMA,stage,executingCollectorPath:actual,relativePath:portable(prep.release.expectedExtractionRoot,actual),canonicalPath:actual,size:c.size,sha256:c.sha256,releaseRoot:prep.release.expectedExtractionRoot,releaseIdentity:prep.installationBinding.releaseIdentity,releaseManifestDigest:prep.release.releaseManifestDigest,extractedTreeDigest:prep.release.extractedTreeDigest,runtimePath:runtime,runtimeSize:c.runtimeSize,runtimeSha256:c.runtimeSha256,processId:processIdentity.processId??process.pid,parentProcessId:processIdentity.parentProcessId??process.ppid,proofSid:processIdentity.proofSid??prep.expectedProofSid,windowsSessionId:processIdentity.windowsSessionId??process.env.SESSIONNAME,proofSessionId:prep.sessionId,nonce:prep.nonce,collectionTimestamp:processIdentity.collectionTimestamp??new Date().toISOString()}}
export function buildBootStageRecord(prep:any,stage:BootStageName,boot:any,collector:any,extra:any={}):any{const identity=readVerifiedInstallationIdentity(prep);return{schemaVersion:BOOT_STAGE_SCHEMA,stage,bootIdentity:boot.bootIdentity,lastBoot:boot.lastBoot,bootRecord:boot.bootRecord,hostProfileId:prep.hostProfileId,installationIdentity:identity.installationId,installationIdentityRecordDigest:prep.installationIdentityRecord.sha256,releaseIdentity:prep.installationBinding.releaseIdentity,releaseManifestDigest:prep.release.releaseManifestDigest,extractedTreeDigest:prep.release.extractedTreeDigest,subjectCollectorPath:collector.canonicalPath,subjectCollectorDigest:collector.sha256,subjectCollectorRuntime:collector.runtimePath,bundledRuntimeDigest:collector.runtimeSha256,subjectSid:collector.proofSid,windowsSessionId:collector.windowsSessionId,proofSessionId:prep.sessionId,nonce:prep.nonce,observerDigest:extra.observerDigest??collector.sha256,collectionTimestamp:boot.collectedAt,rawBootObservationArtifactPath:extra.rawBootObservationArtifactPath,rawBootObservationDigest:extra.rawBootObservationDigest,...extra}}
export function emitSubjectBindingRecords(root:string,prep:any,stage:BootStageName,boot:any,processIdentity:any={}):any{const collector=buildSubjectCollectorIdentity(prep,stage,processIdentity),prefix=stage==="PRE_RESTART"?"pre":"post",rawPath=`${prefix}/boot-observation.json`;if(!fs.existsSync(path.join(root,...rawPath.split("/"))))writeEvidenceArtifact(root,rawPath,boot);const record=buildBootStageRecord(prep,stage,boot,collector,{rawBootObservationArtifactPath:rawPath,rawBootObservationDigest:sha256File(path.join(root,...rawPath.split("/")))});writeEvidenceArtifact(root,`${prefix}/subject-collector-identity.json`,collector);writeEvidenceArtifact(root,`${prefix}/boot-stage.json`,record);if(stage==="POST_RESTART"){for(const name of ["pre-boot-observation.json","pre-boot-stage.json","post-boot-observation.json","post-boot-stage.json"]){const source=path.join(prep.observerRoot,name);if(!fs.existsSync(source))throw new Error("OBSERVER_BOOT_STAGE_REQUIRED");writeEvidenceArtifact(root,`observer/${name}`,fs.readFileSync(source))}const identityTarget=path.join(root,"installation","installation-identity.json");writeEvidenceArtifact(root,"installation/installation-identity.json",fs.readFileSync(prep.installationIdentityRecord.path));if(sha256File(identityTarget)!==sha256File(prep.installationIdentityRecord.path))throw new Error("INSTALLATION_IDENTITY_MISMATCH")};return{collector,bootStage:record}}
export function emitObserverBootStage(root:string,prep:any,stage:BootStageName,boot:any,observer:any):any{const collector=buildSubjectCollectorIdentity(prep,stage,{proofSid:prep.expectedProofSid,windowsSessionId:observer.windowsSessionId,collectionTimestamp:boot.collectedAt}),raw=`${stage==="PRE_RESTART"?"pre":"post"}-boot-observation.json`;if(!fs.existsSync(path.join(root,raw)))writeEvidenceArtifact(root,raw,boot);const record=buildBootStageRecord(prep,stage,boot,collector,{observerDigest:observer.observerSha256,privilegedObserverPath:observer.observerPath,privilegedObserverDigest:observer.observerSha256,processMonitorDigest:observer.monitorSha256,observerSid:observer.observerSid,observerProcessId:observer.pid,observerReadyTimestamp:observer.observerReadyAt,rawBootObservationArtifactPath:raw,rawBootObservationDigest:sha256File(path.join(root,raw))});writeEvidenceArtifact(root,`${stage==="PRE_RESTART"?"pre":"post"}-boot-stage.json`,record);return record}

function requireRoundTrip(prep:any):any{if(prep.invocationMode!=="NON_PROMOTABLE_PRODUCTION_ROUNDTRIP_TEST"||!prep.roundTripAdapters)throw new Error("ROUNDTRIP_TEST_ADAPTER_PROHIBITED");return prep.roundTripAdapters}
export function runPackagedRoundTripObserver(preparationPath:string,stage:BootStageName,identity:any):any{const prep=read(preparationPath),adapters=requireRoundTrip(prep),root=path.resolve(prep.observerRoot),boot=stage==="PRE_RESTART"?adapters.preBoot:adapters.postBoot,releaseRoot=prep.release.expectedExtractionRoot,observerPath=identity.observerPath,monitorPath=identity.monitorPath,runtimePath=identity.runtimePath;fs.mkdirSync(root,{recursive:true});const start={schemaVersion:"sera.privileged-observer-start.v1",invocation:prep.invocationMode,stage,sessionId:prep.sessionId,nonce:prep.nonce,subjectSid:prep.expectedProofSid,observerSid:adapters.observerSid,hostProfileId:prep.hostProfileId,releaseIdentity:prep.installationBinding.releaseIdentity,elevated:false,roundTripTestAdapter:true,pid:process.pid,observerPath,observerSha256:sha256File(observerPath),monitorPath,monitorSha256:sha256File(monitorPath),runtimePath,runtimeSha256:sha256File(runtimePath),observerReadyAt:boot.collectedAt,windowsSessionId:adapters.observerSessionId};fs.writeFileSync(path.join(root,"observer-start.json"),`${JSON.stringify(start,null,2)}\n`);writeEvidenceArtifact(root,`${stage==="PRE_RESTART"?"pre":"post"}-observer-start.json`,start);writeEvidenceArtifact(root,`${stage==="PRE_RESTART"?"pre":"post"}-observer-ready.json`,{...start,ready:true,sourceEventType:"ROUNDTRIP_TEST_ADAPTER",liveSubscription:false});const record=emitObserverBootStage(root,prep,stage,boot,start);writeEvidenceArtifact(root,`${stage==="PRE_RESTART"?"pre":"post"}-monitor-events.json`,{invocation:prep.invocationMode,events:adapters.processEvents??[],sessionId:prep.sessionId,nonce:prep.nonce});const complete={schemaVersion:"sera.live-process-monitor-complete.v1",invocation:prep.invocationMode,stage,sessionId:prep.sessionId,nonce:prep.nonce,flushed:true,unsubscribed:true,monitorStoppedAt:boot.collectedAt};fs.writeFileSync(path.join(root,"monitor-complete.json"),`${JSON.stringify(complete,null,2)}\n`);writeEvidenceArtifact(root,`${stage==="PRE_RESTART"?"pre":"post"}-monitor-complete.json`,complete);return{ok:true,status:"NON_PROMOTABLE_PRODUCTION_ROUNDTRIP_TEST",stage,pid:process.pid,observerRoot:root,bootStage:record,claimsGranted:[]}}
export function runPackagedRoundTripSubject(preparationPath:string,stage:BootStageName,identity:any):any{const prep=read(preparationPath),adapters=requireRoundTrip(prep),root=path.dirname(path.resolve(preparationPath)),boot=stage==="PRE_RESTART"?adapters.preBoot:adapters.postBoot,result=emitSubjectBindingRecords(root,prep,stage,boot,{runtimePath:identity.runtimePath,processId:process.pid,parentProcessId:process.ppid,proofSid:prep.expectedProofSid,windowsSessionId:adapters.subjectSessionId});if(stage==="PRE_RESTART"){writeEvidenceArtifact(root,"pre/workflow-start.json",{invocation:prep.invocationMode,workflowStartedAt:boot.collectedAt,sessionId:prep.sessionId,nonce:prep.nonce})}else{writeEvidenceArtifact(root,"pre/workflow-complete.json",{invocation:prep.invocationMode,workflowCompletedAt:boot.collectedAt,sessionId:prep.sessionId,nonce:prep.nonce});if(!fs.existsSync(path.join(root,"governance-decision.json")))fs.copyFileSync(prep.governanceDecisionPath,path.join(root,"governance-decision.json"));const manifest=finalizeEvidenceManifest({root,profileId:prep.profileId,evidenceMode:"governed-windows-v2",sessionId:prep.sessionId,nonce:prep.nonce,proofSid:prep.expectedProofSid,collectorId:"sera-windows-collector/v5.6-roundtrip",collectorSha256:prep.subjectCollector.sha256,installationIdentity:prep.installationIdentity,installationIdentityRecordDigest:prep.installationIdentityRecord.sha256,subjectCollectorDigest:prep.subjectCollector.sha256,preparationManifestDigest:sha256File(preparationPath),governanceDecisionDigest:sha256File(path.join(root,"governance-decision.json")),stageFor:p=>p.startsWith("post/")||p.startsWith("observer/post-")?"post-restart":p.startsWith("pre/")||p.startsWith("observer/pre-")?"pre-restart":"preparation"});return{ok:true,status:"NON_PROMOTABLE_PRODUCTION_ROUNDTRIP_TEST",stage,pid:process.pid,manifestPath:path.join(root,"restricted-user-evidence-manifest.json"),manifestDigest:manifest.manifestDigest,collector:result.collector,claimsGranted:[]}}return{ok:true,status:"NON_PROMOTABLE_PRODUCTION_ROUNDTRIP_TEST",stage,pid:process.pid,collector:result.collector,claimsGranted:[]}}
