import fs from "node:fs";
import path from "node:path";
import { EVIDENCE_MANIFEST_FILE, EVIDENCE_MANIFEST_SCHEMA, listBundleFiles, manifestDigest, normalizedTreeDigest, readJson, safeArtifactPath, sha256File, type EvidenceManifest } from "./restricted-user-evidence";
import { captureStage, collectPostRestart, collectPreRestart, createPreparationManifest } from "./restricted-user-observations";
import { auditLiveBinding } from "./restricted-user-live-binding";
import { deriveSubjectProcessTree, verifyPrivilegedObserverEvidence } from "./restricted-user-privileged-observer";
import { auditIdentityBindings } from "./restricted-user-identity-binding";
import { prepareProductionIdentityBindings,readVerifiedInstallationIdentity,RESTRICTED_INVOCATION_MODES,type RestrictedInvocationMode } from "./restricted-user-production-bindings";

export const RESTRICTED_USER_PROFILE_ID = "same-host-restricted-user-release-only-v1";
export const RESTRICTED_USER_MODEL = "llama3.2:1b";
export const RESTRICTED_USER_NEGATIVE_CASES = ["development-account-used", "administrator-account-used", "proof-account-in-administrators", "release-inside-repository", "repository-readable", "git-readable", "development-database-readable", "development-path-inherited", "system-node-used", "development-tool-executed", "bundled-runtime-missing", "bundled-runtime-altered", "public-adapter-enabled", "public-endpoint-reachable", "ollama-not-loopback", "model-digest-mismatch", "visual-evidence-missing", "restart-evidence-missing", "reparse-point-escape", "cross-host-claim"] as const;
export const RESTRICTED_USER_REASON_CODES = {
  developmentAccount: "ACCOUNT_DEVELOPMENT_SID_USED", administrator: "TOKEN_ELEVATED", administratorsGroup: "TOKEN_ADMINISTRATORS_GROUP_ENABLED",
  releaseInsideRepository: "RELEASE_INSIDE_REPOSITORY", repositoryReadable: "REPOSITORY_NOT_DENIED", gitReadable: "GIT_NOT_DENIED", databaseReadable: "DEVELOPMENT_DATABASE_NOT_DENIED",
  inheritedPath: "DEVELOPMENT_PATH_IN_ENVIRONMENT", systemNode: "RUNTIME_NOT_BUNDLED", prohibitedProcess: "PROHIBITED_PROCESS_OBSERVED", runtimeMissing: "BUNDLED_RUNTIME_MISSING",
  runtimeAltered: "BUNDLED_RUNTIME_DIGEST_MISMATCH", publicAdapter: "PUBLIC_ADAPTER_ENABLED", publicReachable: "PUBLIC_ENDPOINT_REACHABLE", ollamaRemote: "OLLAMA_REMOTE_NOT_LOOPBACK",
  modelMismatch: "MODEL_IDENTITY_MISMATCH", visualMissing: "VISUAL_STAGE_MISSING", restartMissing: "WINDOWS_BOOT_IDENTITY_UNCHANGED", pathEscape: "REPARSE_OR_PATH_ESCAPE",
  crossHost: "CROSS_HOST_CLAIM_PROHIBITED"
} as const;

const REQUIRED_JSON = ["preparation-manifest.json","governance-decision.json","installation/installation-identity.json","pre/collector-provenance.json","pre/subject-collector-identity.json","pre/boot-observation.json","pre/boot-stage.json","observer/pre-boot-observation.json","observer/pre-boot-stage.json","pre/workflow-start.json","pre/workflow-complete.json","pre/account-token.json","pre/source-denial.json","pre/release-runtime.json","pre/process-events.json","pre/environment.json","pre/ollama.json","pre/network.json","pre/desktop.json","pre/persistence.json","post/subject-collector-identity.json","post/boot-observation.json","post/boot-stage.json","observer/post-boot-observation.json","observer/post-boot-stage.json","post/restart.json","post/persistence.json","post/recurrence.json","negative-cases.json"];
const VISUAL_STAGES = ["packaged-launcher", "desktop-operator-loaded", "runtime-health", "supported-intake", "provenance", "model-candidate", "evaluation", "operator-review", "digest-bound-approval", "closeout", "evidence-history"];
const DENIAL_ROLES = ["repository-root", "repository-git", "repository-node-modules", "repository-sera", "development-sqlite", "development-codex", "sera-sandbox", "dev-root", "configured-private-root"];
const PROHIBITED = ["git", "npm", "npx", "codex", "code", "devenv", "cl", "msbuild", "winget", "choco"];
const SOURCE_OPERATIONS = ["identity", "enumerate", "known-child-read", "file-open", "execution", "reparse-inspection", "parent-traversal"];
const ENVIRONMENT_COVERAGE = ["PATH", "PATHEXT", "SystemRoot", "WINDIR", "TEMP", "TMP", "USERPROFILE", "LOCALAPPDATA", "APPDATA", "NODE_PATH", "NODE_OPTIONS", "npm_config_*", "NPM_CONFIG_*", "GIT_*", "CODEX_*", "PROXY_*", "CLOUD_CREDENTIALS", "PROVIDER_CREDENTIALS", "DEVELOPMENT_PATHS"];

export interface RestrictedUserVerification { ok: boolean; status: "RESTRICTED_PROOF_VERIFIED" | "BLOCKED"; profileId: string; reasonCodes: string[]; grantedClaims: string[]; deniedClaims: ["CROSS_HOST_PORTABILITY_PROVEN"]; manifestDigest?: string; installationIdentityVerified?:boolean; subjectCollectorVerified?:boolean; preRestartBootStageVerified?:boolean; postRestartBootStageVerified?:boolean; windowsRestartVerified?:boolean; }
const digest = /^[a-f0-9]{64}$/;
const GOVERNANCE_DECISION_SHA256 = "a8a530ea3cd3f1e4c57f1b0209075ecaf2f074f707757b1acfc283df9d633190";
const loopback = (value: string) => value === "127.0.0.1" || value === "::1";

export function restrictedUserPolicy(): Record<string, unknown> { return { schemaVersion: "sera.restricted-user-release-only-policy.v2", profileId: RESTRICTED_USER_PROFILE_ID, allowedClaims: ["RELEASE_INDEPENDENCE_PROVEN", "CERTIFIED_HOST_PROFILE_PROVEN"], deniedClaims: ["CROSS_HOST_PORTABILITY_PROVEN"], threatModel: "Operational same-host evidence; no malicious-administrator, kernel, firmware, collector-control, or hardware-backed attestation claim.", model: RESTRICTED_USER_MODEL, preparationIsPlanOnly: true, collectionRequiresRealRestrictedEnvironment: true, milestone16Complete: false, currentCertification: "fresh-process-offline-restart-relocated-root-lesson-persistence-proof-v1" }; }

export function prepareRestrictedUserProof(input: any = {}): Record<string, unknown> {
  if (!input.releaseZip || !input.releaseManifest || !input.extractionRoot || !input.proofAccountName || !input.proofSid || !input.developmentSid || !input.hostProfileId || !input.governanceDecision || !input.observerRoot || !Array.isArray(input.collectorFiles)) return { ok: false, status: "BLOCKED", reasonCodes: ["PREPARATION_INPUTS_REQUIRED"], executesSystemChanges: false };
  const invocationMode:RestrictedInvocationMode=input.invocationMode??"NON_PROMOTABLE_DEVELOPMENT_SMOKE";if(!RESTRICTED_INVOCATION_MODES.includes(invocationMode))return{ok:false,status:"BLOCKED",reasonCodes:["PREPARATION_INVOCATION_MODE_REQUIRED"],executesSystemChanges:false};const outputRoot=path.resolve(input.outputRoot??path.join(process.cwd(),".sera","base-mvp","restricted-user-plan")),existingPath=path.join(outputRoot,"preparation-manifest.json");
  if(fs.existsSync(existingPath)){const existing=readJson(existingPath),same=existing.invocationMode===invocationMode&&existing.hostProfileId===input.hostProfileId&&existing.expectedProofSid===input.proofSid&&existing.developmentSid===input.developmentSid&&path.resolve(existing.observerRoot)===path.resolve(input.observerRoot)&&existing.release?.zipSha256===sha256File(input.releaseZip)&&existing.release?.releaseManifestDigest===sha256File(input.releaseManifest)&&path.resolve(existing.release?.expectedExtractionRoot??"")===path.resolve(input.extractionRoot);if(!same)return{ok:false,status:"BLOCKED",reasonCodes:["PREPARATION_CONFLICT"],executesSystemChanges:false};try{readVerifiedInstallationIdentity(existing)}catch{return{ok:false,status:"BLOCKED",reasonCodes:["INSTALLATION_IDENTITY_MALFORMED"],executesSystemChanges:false}}return{ok:true,status:"PREPARATION_REUSED",path:existingPath,sessionId:existing.sessionId,installationIdentity:existing.installationIdentity,installationIdentityRecord:existing.installationIdentityRecord,subjectCollector:existing.subjectCollector,executesSystemChanges:false}}
  const result:any=createPreparationManifest({ projectRoot: input.projectRoot ?? process.cwd(), outputRoot, releaseZip: input.releaseZip, extractionRoot: input.extractionRoot, releaseManifest: input.releaseManifest, collectorFiles: input.collectorFiles, proofAccountName: input.proofAccountName, proofSid: input.proofSid, developmentSid: input.developmentSid, hostProfileId: input.hostProfileId, governanceDecision: input.governanceDecision, observerRoot:path.resolve(input.observerRoot), developmentStatePaths: input.developmentStatePaths, networkRestorationState: input.networkRestorationState });const prepared=prepareProductionIdentityBindings(result.path,{invocationMode,roundTripAdapters:input.roundTripAdapters});return { ...result,status:"PREPARATION_CREATED", installationIdentity:prepared.installationIdentity, installationIdentityRecord:prepared.installationIdentityRecord, subjectCollector:prepared.subjectCollector, executesSystemChanges: false };
}
export const collectRestrictedUserPreRestart = (preparation: string) => collectPreRestart(preparation);
export const collectRestrictedUserPostRestart = (preparation: string) => collectPostRestart(preparation);
export const captureRestrictedUserStage = (stage: string, preparation: string) => captureStage(stage, preparation);

export function verifyRestrictedUserEvidence(rootInput: string): RestrictedUserVerification {
  const root = path.resolve(rootInput); const reasons: string[] = []; const fail = (code: string, pass: boolean) => { if (!pass && !reasons.includes(code)) reasons.push(code); };
  if (!fs.existsSync(root) || !fs.statSync(root).isDirectory()) return blocked(["EVIDENCE_ROOT_REQUIRED"]);
  const manifestPath = path.join(root, EVIDENCE_MANIFEST_FILE); if (!fs.existsSync(manifestPath)) return blocked(["EVIDENCE_MANIFEST_MISSING"]);
  let manifest: EvidenceManifest; try { manifest = readJson(manifestPath); } catch { return blocked(["EVIDENCE_MANIFEST_INVALID"]); }
  fail("MANIFEST_SCHEMA_INVALID", manifest.schemaVersion === EVIDENCE_MANIFEST_SCHEMA && manifest.profileId === RESTRICTED_USER_PROFILE_ID);
  const copy: any = { ...manifest }; delete copy.manifestDigest; fail("MANIFEST_DIGEST_MISMATCH", digest.test(manifest.manifestDigest) && manifestDigest(copy) === manifest.manifestDigest);
  const entries = Array.isArray(manifest.files) ? manifest.files : []; const declared = entries.map((e) => e.path);
  fail("DUPLICATE_ARTIFACT", new Set(declared).size === declared.length); fail("MANIFEST_ORDER_INVALID", JSON.stringify(declared) === JSON.stringify([...declared].sort((a, b) => a.localeCompare(b))));
  const actual = listBundleFiles(root).filter((p) => p !== EVIDENCE_MANIFEST_FILE); fail("UNREFERENCED_OR_MISSING_ARTIFACT", JSON.stringify(actual) === JSON.stringify([...declared].sort((a, b) => a.localeCompare(b))));
  for (const required of REQUIRED_JSON) {const bindingArtifact=/installation-identity|subject-collector-identity|boot-observation|boot-stage/.test(required);fail(`REQUIRED_ARTIFACT_MISSING:${required}`,manifest.evidenceMode==="synthetic-test-v2"&&bindingArtifact||declared.includes(required));}
  for (const entry of entries) {
    const full = safeArtifactPath(root, entry.path); fail("UNSAFE_ARTIFACT_PATH", !!full); if (!full || !fs.existsSync(full)) continue;
    const stat = fs.lstatSync(full); fail("ARTIFACT_NOT_REGULAR_FILE", stat.isFile() && !stat.isSymbolicLink()); fail(`ARTIFACT_SIZE_MISMATCH:${entry.path}`, stat.size === entry.size); fail(`ARTIFACT_DIGEST_MISMATCH:${entry.path}`, sha256File(full) === entry.sha256);
    fail("SESSION_BINDING_MISMATCH", entry.sessionId === manifest.sessionId && entry.nonce === manifest.nonce); fail("ARTIFACT_TIMESTAMP_INVALID", !Number.isNaN(Date.parse(entry.capturedAt))); fail("COLLECTOR_DIGEST_INVALID", digest.test(entry.collectorSha256));
  }
  const get = (p: string) => { try { return readJson(path.join(root, ...p.split("/"))); } catch { return {}; } };
  const prep = get("preparation-manifest.json"), governance = get("governance-decision.json"), provenance=get("pre/collector-provenance.json"), workflowStart=get("pre/workflow-start.json"), workflowComplete=get("pre/workflow-complete.json"), account = get("pre/account-token.json"), source = get("pre/source-denial.json"), release = get("pre/release-runtime.json"), processes = get("pre/process-events.json"), env = get("pre/environment.json"), provider = get("pre/ollama.json"), network = get("pre/network.json"), desktop = get("pre/desktop.json"), prePersist = get("pre/persistence.json"), restart = get("post/restart.json"), postPersist = get("post/persistence.json"), recurrence = get("post/recurrence.json"), negatives = get("negative-cases.json");
  fail("PREPARATION_DIGEST_MISMATCH", sha256File(path.join(root, "preparation-manifest.json")) === manifest.preparationManifestDigest); fail("GOVERNANCE_DIGEST_MISMATCH", sha256File(path.join(root, "governance-decision.json")) === manifest.governanceDecisionDigest && prep.governanceDecisionDigest === manifest.governanceDecisionDigest);
  fail("SESSION_NONCE_MISMATCH", prep.sessionId === manifest.sessionId && prep.nonce === manifest.nonce && restart.sessionId === manifest.sessionId && restart.nonce === manifest.nonce);
  fail("GOVERNANCE_BOUNDARY_INVALID", governance.status === "approved" && governance.approvedRole === "project-owner" && governance.approvedProfile === RESTRICTED_USER_PROFILE_ID && JSON.stringify(governance.allowedClaims) === JSON.stringify(["RELEASE_INDEPENDENCE_PROVEN", "CERTIFIED_HOST_PROFILE_PROVEN"]) && governance.prohibitedClaims?.includes("CROSS_HOST_PORTABILITY_PROVEN"));
  const approvedCollectors = new Set((prep.collectors ?? []).map((c: any) => c.sha256)); fail("COLLECTOR_DIGEST_MISMATCH", entries.every((e) => approvedCollectors.has(e.collectorSha256)));
  if (manifest.evidenceMode === "governed-windows-v2") {
    fail("APPROVED_GOVERNANCE_DECISION_MISMATCH", manifest.governanceDecisionDigest === GOVERNANCE_DECISION_SHA256);
    const zipPath = String(prep.release?.zipPath ?? ""), releaseManifestPath = String(prep.release?.releaseManifestPath ?? ""), extractionRoot = String(prep.release?.expectedExtractionRoot ?? "");
    fail("REAL_RELEASE_ZIP_MISSING", fs.existsSync(zipPath) && fs.statSync(zipPath).isFile()); if (fs.existsSync(zipPath)) fail("REAL_RELEASE_ZIP_DIGEST_MISMATCH", sha256File(zipPath) === prep.release.zipSha256);
    fail("REAL_RELEASE_MANIFEST_MISSING", fs.existsSync(releaseManifestPath) && fs.statSync(releaseManifestPath).isFile()); if (fs.existsSync(releaseManifestPath)) fail("REAL_RELEASE_MANIFEST_DIGEST_MISMATCH", sha256File(releaseManifestPath) === prep.release.releaseManifestDigest);
    fail("REAL_EXTRACTION_ROOT_MISSING", fs.existsSync(extractionRoot) && fs.statSync(extractionRoot).isDirectory());
    if (fs.existsSync(extractionRoot)) fail("EXTRACTED_TREE_DIGEST_MISMATCH", normalizedTreeDigest(extractionRoot) === release.treeSha256);
    fail("REAL_COLLECTOR_PROVENANCE_INVALID", (prep.collectors ?? []).length > 0 && (prep.collectors ?? []).every((c: any) => { const p = String(c.path ?? ""); return p.startsWith(`${extractionRoot}${path.sep}`) && fs.existsSync(p) && fs.statSync(p).isFile() && sha256File(p) === c.sha256; }));
    const runtimePath = String(release.runtimePath ?? ""); fail("REAL_RUNTIME_OBSERVATION_INVALID", runtimePath.startsWith(`${extractionRoot}${path.sep}`) && fs.existsSync(runtimePath) && fs.statSync(runtimePath).isFile() && sha256File(runtimePath) === release.runtimeSha256 && fs.statSync(runtimePath).size === release.runtimeSize);
    const releaseManifest=fs.existsSync(releaseManifestPath)?readJson(releaseManifestPath):{},entryCollector=path.join(extractionRoot,"collectors","restricted-user-collector.cjs"),entryMonitor=path.join(extractionRoot,"collectors","process-start-monitor.ps1"),preparedCollector=(prep.collectors??[]).find((c:any)=>c.relativePath==="collectors/restricted-user-collector.cjs"),preparedMonitor=(prep.collectors??[]).find((c:any)=>c.relativePath==="collectors/process-start-monitor.ps1"),manifestCollector=releaseManifest.files?.find((f:any)=>f.path==="collectors/restricted-user-collector.cjs"),manifestMonitor=releaseManifest.files?.find((f:any)=>f.path==="collectors/process-start-monitor.ps1");
    fail("RELEASE_CONTAINED_COLLECTOR_REQUIRED", provenance.invocation==="REAL_RESTRICTED_USER_PROOF"&&provenance.releaseRoot===extractionRoot&&provenance.collectorPath===entryCollector&&provenance.runtimePath===runtimePath&&!provenance.collectorPath.toLowerCase().startsWith(`${String(prep.repository?.canonicalPath).toLowerCase()}${path.sep}`));
    const entryCollectorExists=fs.existsSync(entryCollector)&&fs.statSync(entryCollector).isFile(),entryMonitorExists=fs.existsSync(entryMonitor)&&fs.statSync(entryMonitor).isFile();
    fail("COLLECTOR_CHAIN_OF_CUSTODY_INVALID",entryCollectorExists&&[preparedCollector,manifestCollector].every((r:any)=>r?.sha256===sha256File(entryCollector))&&provenance.collectorSha256===sha256File(entryCollector)&&provenance.collectorSize===fs.statSync(entryCollector).size&&entries.every(e=>e.collectorSha256===provenance.collectorSha256));
    fail("PROCESS_MONITOR_CHAIN_OF_CUSTODY_INVALID",entryMonitorExists&&[preparedMonitor,manifestMonitor].every((r:any)=>r?.sha256===sha256File(entryMonitor))&&provenance.monitorSha256===sha256File(entryMonitor)&&provenance.monitorSize===fs.statSync(entryMonitor).size);
    fail("COLLECTOR_PROCESS_IDENTITY_MISMATCH",provenance.runtimePid===provenance.collectorPid&&provenance.collectorPid===release.pid&&provenance.sessionId===manifest.sessionId&&provenance.nonce===manifest.nonce&&provenance.proofSid===account.proofSid);
    fail("EVIDENCE_PREPARATION_SEQUENCE_INVALID",Date.parse(prep.preparedAt)<=Date.parse(provenance.startedAt)&&entries.every(e=>Date.parse(e.capturedAt)>=Date.parse(prep.preparedAt)));
    for(const code of auditLiveBinding({releaseRoot:extractionRoot,repositoryRoot:String(prep.repository?.canonicalPath),releaseManifest,preparation:prep,evidenceManifest:manifest,provenance,monitor:processes,workflowStart,workflowComplete,runtimePath,collectorPath:entryCollector,monitorPath:entryMonitor,proofSid:account.proofSid}))fail(code,false);
  }
  fail(RESTRICTED_USER_REASON_CODES.developmentAccount, account.proofSid !== prep.developmentSid); fail("ACTIVE_TOKEN_SID_MISMATCH", account.activeTokenSid === account.proofSid); fail(RESTRICTED_USER_REASON_CODES.administrator, account.elevationType === "limited" && account.tokenElevated === false); fail(RESTRICTED_USER_REASON_CODES.administratorsGroup, !(account.enabledGroupSids ?? []).includes("S-1-5-32-544")); fail("LOCAL_STANDARD_ACCOUNT_NOT_OBSERVED", account.accountSource === "Local" && account.standardLocalAccount === true && account.profileSid === account.proofSid && !!account.profilePath && !!account.profileCreatedAt);
  fail("ACCOUNT_RAW_OBSERVATIONS_MISSING", account.collectorExecutable === "C:\\Windows\\System32\\whoami.exe" && [account.rawIdentitySha256, account.rawGroupsSha256, account.rawTokenSha256].every((v: any) => digest.test(v)) && !Number.isNaN(Date.parse(account.capturedAt)));
  const observations = source.observations ?? []; for (const role of DENIAL_ROLES) fail(`${role.toUpperCase().replace(/-/g, "_")}_PROBE_MISSING`, observations.some((o: any) => o.targetRole === role));
  fail("SOURCE_OPERATION_COVERAGE_INCOMPLETE", DENIAL_ROLES.every((role) => SOURCE_OPERATIONS.every((operation) => observations.some((o: any) => o.targetRole === role && o.operation === operation))));
  fail("SOURCE_OBSERVATION_METADATA_INVALID", observations.every((o: any) => !!o.requestedPath && !!o.normalizedPath && path.isAbsolute(o.normalizedPath) && o.proofSid === account.proofSid && !Number.isNaN(Date.parse(o.timestamp)) && Number.isInteger(o.windowsErrorCode)));
  const denied = (role: string) => observations.filter((o: any) => o.targetRole === role).every((o: any) => ["EXISTS_ACCESS_DENIED", "ABSENT"].includes(o.classification) && o.proofSid === account.proofSid && Number.isInteger(o.windowsErrorCode));
  const existsDenied = (role: string) => observations.filter((o: any) => o.targetRole === role).every((o: any) => o.classification === "EXISTS_ACCESS_DENIED");
  const accessBlocked = (role: string) => observations.filter((o: any) => o.targetRole === role && ["enumerate", "known-child-read", "file-open", "execution"].includes(o.operation)).every((o: any) => ["EXISTS_ACCESS_DENIED", "ABSENT"].includes(o.classification));
  fail(RESTRICTED_USER_REASON_CODES.repositoryReadable, accessBlocked("repository-root") && observations.some((o: any) => o.targetRole === "repository-root" && o.classification === "EXISTS_ACCESS_DENIED")); fail(RESTRICTED_USER_REASON_CODES.gitReadable, accessBlocked("repository-git") && observations.some((o: any) => o.targetRole === "repository-git" && o.classification === "EXISTS_ACCESS_DENIED")); fail(RESTRICTED_USER_REASON_CODES.databaseReadable, accessBlocked("development-sqlite") && observations.some((o: any) => o.targetRole === "development-sqlite" && o.classification === "EXISTS_ACCESS_DENIED")); fail(RESTRICTED_USER_REASON_CODES.pathEscape, observations.every((o: any) => o.classification !== "REPARSE_ESCAPE" && o.classification !== "PROBE_ERROR" && (o.operation !== "parent-traversal" || o.parentTraversalBlocked === true)));
  const repo = String(prep.repository?.canonicalPath ?? "").toLowerCase(), releaseRoot = String(release.releaseRoot ?? ""); fail(RESTRICTED_USER_REASON_CODES.releaseInsideRepository, !!releaseRoot && !releaseRoot.toLowerCase().startsWith(`${repo}${path.sep}`) && releaseRoot.includes(" ") && !release.releaseRootIsUnc);
  fail(RESTRICTED_USER_REASON_CODES.runtimeMissing, release.runtimeExists === true); fail(RESTRICTED_USER_REASON_CODES.runtimeAltered, release.zipSha256 === prep.release?.zipSha256 && release.releaseManifestDigest === prep.release?.releaseManifestDigest && digest.test(release.treeSha256) && release.runtimeSha256 === release.observedExecutableSha256 && release.runtimeSize === release.observedExecutableSize);
  fail(RESTRICTED_USER_REASON_CODES.systemNode, release.observedExecutablePath === release.runtimePath && release.execPath === release.runtimePath && release.explicitReleaseRelativeLaunch === true && release.shellUsed === false && release.launcherKind === "packaged");
  fail("RUNTIME_PROCESS_OBSERVATION_INVALID", !!release.processVersion && !!release.processArch && release.parentPid > 0 && Array.isArray(release.arguments) && release.sessionId === manifest.sessionId && release.proofSid === account.proofSid && !Number.isNaN(Date.parse(release.startedAt)));
  fail("PROCESS_MONITOR_INCOMPLETE", processes.liveSubscription===true&&processes.sourceEventType==="Win32_ProcessStartTrace"&&processes.readyHandshake === true && processes.completeness === "COMPLETE" && processes.sessionId === manifest.sessionId && processes.nonce===manifest.nonce&&processes.proofSid === account.proofSid && Date.parse(processes.startedAt) < Date.parse(workflowStart.workflowStartedAt)&&Date.parse(processes.stoppedAt)>Date.parse(workflowComplete.workflowCompletedAt)&&workflowStart.sessionId===manifest.sessionId&&workflowComplete.nonce===manifest.nonce&&(processes.events ?? []).every((e: any) => Number.isInteger(e.pid) && Number.isInteger(e.parentPid) && !!e.executableName && !!e.timestamp&&!!e.sourceEventType&&!!e.enrichmentStatus)); fail(RESTRICTED_USER_REASON_CODES.prohibitedProcess, !(processes.events ?? []).some((e: any) => PROHIBITED.includes(String(e.executableName).toLowerCase().replace(/\.(exe|cmd)$/,"")) || e.prohibited === true));
  const wrongNode=(processes.events??[]).some((e:any)=>String(e.executableName).toLowerCase()==="node.exe"&&e.executablePath&&path.resolve(e.executablePath).toLowerCase()!==path.resolve(release.runtimePath).toLowerCase());fail("SYSTEM_NODE_OBSERVED",!wrongNode);
  fail(RESTRICTED_USER_REASON_CODES.inheritedPath, env.pid === release.pid && env.sessionId === manifest.sessionId && env.createdFromAllowlist === true && env.secretValueWritten === false && env.developmentPathPresent === false && ENVIRONMENT_COVERAGE.every((key) => env.coverage?.includes(key)) && (env.entries ?? []).every((e: any) => !Object.hasOwn(e, "value") && ["present-redacted", "absent", "digest-only"].includes(e.classification)));
  fail(RESTRICTED_USER_REASON_CODES.ollamaRemote, provider.endpointHost === "127.0.0.1" && loopback(provider.socketRemoteAddress)); fail(RESTRICTED_USER_REASON_CODES.modelMismatch, provider.providerId === "ollama-loopback-base-mvp-v1" && provider.model === RESTRICTED_USER_MODEL && provider.observedModel === RESTRICTED_USER_MODEL && digest.test(provider.modelDigest) && digest.test(provider.requestSha256) && digest.test(provider.responseSha256) && provider.candidateOnly === true && provider.authorities?.length === 0);
  const requestEntry = entries.find((e) => e.path === provider.requestArtifact), responseEntry = entries.find((e) => e.path === provider.responseArtifact); fail("PROVIDER_BYTE_ARTIFACT_INVALID", !!provider.providerVersion && requestEntry?.sha256 === provider.requestSha256 && responseEntry?.sha256 === provider.responseSha256 && !!provider.requestedAt && !!provider.respondedAt);
  fail(RESTRICTED_USER_REASON_CODES.publicAdapter, (network.adapters ?? []).every((a: any) => a.interfaceGuid && Number.isInteger(a.interfaceIndex) && a.name && a.description && a.operationalStatus && a.administrativeStatus && a.ipv4State && a.ipv6State && (a.type === "loopback" || (a.publicRouteCapable ? a.administrativeStatus === "disabled" && a.inRestorationManifest === true : true))) && network.inventoryComplete === true && Array.isArray(network.routes));
  fail(RESTRICTED_USER_REASON_CODES.publicReachable, network.publicDns === "FAILED" && network.publicIpv4Tcp === "FAILED" && ["FAILED", "UNAVAILABLE"].includes(network.publicIpv6) && network.publicHttp === "FAILED" && network.publicHttps === "FAILED" && network.localhost === "SUCCEEDED" && network.ollama === "SUCCEEDED" && network.desktopOperator === "SUCCEEDED");
  const visuals = entries.filter((e) => e.artifactType === "visual-capture"); fail(RESTRICTED_USER_REASON_CODES.visualMissing, VISUAL_STAGES.every((stage) => desktop.stages?.some((s: any) => s.stage === stage && visuals.some((v) => v.path === s.imagePath) && s.proofSid === account.proofSid && s.sessionId === manifest.sessionId && s.releaseIdentity === release.releaseIdentity && !!s.capturedAt)));
  fail(RESTRICTED_USER_REASON_CODES.restartMissing, restart.bootIdentityBefore && restart.bootIdentityAfter && restart.bootIdentityBefore !== restart.bootIdentityAfter && restart.bootRecordBefore && restart.bootRecordAfter && restart.bootRecordBefore !== restart.bootRecordAfter && Date.parse(restart.lastBootAfter) > Date.parse(restart.lastBootBefore) && Date.parse(restart.collectedAfter) > Date.parse(restart.collectedBefore) && restart.processIdBefore !== restart.processIdAfter);
  fail("PERSISTENCE_RECOVERY_INVALID", prePersist.installationId === postPersist.installationId && prep.hostProfileId === restart.hostProfileId && ["state", "history", "artifact", "evidence", "preventionRule"].every((k) => postPersist.recovered?.[k] === true)); fail("RECURRENCE_RESULTS_INVALID", ["exactFailurePrevention", "equivalentFailurePrevention", "relatedContextWarning", "outOfScopeNonBlocking"].every((k) => recurrence[k] === "PASS"));
  fail(RESTRICTED_USER_REASON_CODES.crossHost, negatives.crossHostPortabilityClaimed === false); for (const id of RESTRICTED_USER_NEGATIVE_CASES) fail(`NEGATIVE_CASE_MISSING:${id}`, negatives.results?.[id] === "PASS");
  fail("SYNTHETIC_EVIDENCE_NON_PROMOTABLE", manifest.evidenceMode === "governed-windows-v2" && prep.evidenceMode === "governed-windows-v2" && entries.every((e) => e.collectorId.startsWith("sera-windows-collector/")));
  if(prep.observerProfile==="privileged-observer-sidecar-v1"){
    for(const code of ["REQUIRED_ARTIFACT_MISSING:pre/process-events.json","PROCESS_MONITOR_INCOMPLETE","SYSTEM_NODE_OBSERVED"]){const index=reasons.indexOf(code);if(index>=0)reasons.splice(index,1)}
    const observerBinding=get("pre/observer-ready-binding.json");
    fail("PRIVILEGED_OBSERVER_READY_REQUIRED",observerBinding.liveSubscription===true&&observerBinding.sourceEventType==="Win32_ProcessStartTrace"&&observerBinding.sessionId===manifest.sessionId&&observerBinding.nonce===manifest.nonce&&observerBinding.subjectSid===account.proofSid);
  }
  const ok = reasons.length === 0; return { ok, status: ok ? "RESTRICTED_PROOF_VERIFIED" : "BLOCKED", profileId: RESTRICTED_USER_PROFILE_ID, reasonCodes: reasons.sort(), grantedClaims: [], deniedClaims: ["CROSS_HOST_PORTABILITY_PROVEN"], manifestDigest: manifest.manifestDigest };
}

export const proveRestrictedUserEvidence = (root?: string) => root ? verifyRestrictedUserEvidence(root) : blocked(["REAL_EVIDENCE_BUNDLE_REQUIRED"]);
export const inspectRestrictedUserEvidence = (root: string) => ({ root: path.resolve(root), verification: verifyRestrictedUserEvidence(root) });

export function verifyIntegratedRestrictedUserEvidence(subjectRootInput?:string,observerRootInput?:string):RestrictedUserVerification{
  if(!subjectRootInput||!fs.existsSync(path.resolve(subjectRootInput)))return blocked(["SUBJECT_EVIDENCE_ROOT_REQUIRED"]);
  if(!observerRootInput||!fs.existsSync(path.resolve(observerRootInput)))return blocked(["OBSERVER_EVIDENCE_ROOT_REQUIRED"]);
  const subjectRoot=path.resolve(subjectRootInput),observerRoot=path.resolve(observerRootInput),subjectResult=verifyRestrictedUserEvidence(subjectRoot),observerResult:any=verifyPrivilegedObserverEvidence(subjectRoot,observerRoot),read=(root:string,rel:string)=>{try{return readJson(path.join(root,...rel.split("/")))}catch{return {}}},prep=read(subjectRoot,"preparation-manifest.json"),account=read(subjectRoot,"pre/account-token.json"),workflowStart=read(subjectRoot,"pre/workflow-start.json"),workflowComplete=read(subjectRoot,"pre/workflow-complete.json"),observerStart=read(observerRoot,"observer-start.json"),observerComplete=read(observerRoot,"monitor-complete.json"),reasons=[...subjectResult.reasonCodes,...(observerResult.reasonCodes??[])],fail=(c:string,p:boolean)=>{if(!p&&!reasons.includes(c))reasons.push(c)};
  fail("OBSERVER_ROOT_MISMATCH",path.resolve(prep.observerRoot??"")===observerRoot);
  const immutableManifest=read(subjectRoot,EVIDENCE_MANIFEST_FILE),installationCopyPath=path.join(subjectRoot,"installation","installation-identity.json"),subjectCollectorPre=read(subjectRoot,"pre/subject-collector-identity.json"),subjectCollectorPost=read(subjectRoot,"post/subject-collector-identity.json"),requiredBindingPaths=["installation/installation-identity.json","pre/subject-collector-identity.json","pre/boot-observation.json","pre/boot-stage.json","observer/pre-boot-observation.json","observer/pre-boot-stage.json","post/subject-collector-identity.json","post/boot-observation.json","post/boot-stage.json","observer/post-boot-observation.json","observer/post-boot-stage.json"];
  fail("IDENTITY_MANIFEST_CLOSURE_REQUIRED",requiredBindingPaths.every(p=>immutableManifest.files?.some((e:any)=>e.path===p)));
  const installationSource=String(prep.installationIdentityRecord?.path??"");fail("INSTALLATION_IDENTITY_COPY_REQUIRED",fs.existsSync(installationSource)&&fs.existsSync(installationCopyPath)&&sha256File(installationSource)===sha256File(installationCopyPath)&&fs.statSync(installationSource).size===fs.statSync(installationCopyPath).size&&sha256File(installationSource)===prep.installationIdentityRecord?.sha256&&fs.statSync(installationSource).size===prep.installationIdentityRecord?.size&&immutableManifest.installationIdentityRecordDigest===prep.installationIdentityRecord?.sha256);
  fail("SUBJECT_COLLECTOR_IDENTITY_REQUIRED",subjectCollectorPre.sha256&&subjectCollectorPre.sha256===subjectCollectorPost.sha256&&subjectCollectorPre.sha256===prep.subjectCollector?.sha256&&subjectCollectorPre.canonicalPath===subjectCollectorPost.canonicalPath&&subjectCollectorPre.canonicalPath===prep.subjectCollector?.canonicalPath);
  fail("OBSERVER_DEVELOPMENT_SMOKE_NON_PROMOTABLE",observerStart.invocation==="REAL_RESTRICTED_USER_PROOF");
  fail("CROSS_ROOT_SESSION_MISMATCH",prep.sessionId===observerStart.sessionId&&prep.sessionId===observerComplete.sessionId);
  fail("CROSS_ROOT_NONCE_MISMATCH",prep.nonce===observerStart.nonce&&prep.nonce===observerComplete.nonce);
  fail("CROSS_ROOT_SUBJECT_SID_MISMATCH",prep.expectedProofSid===observerStart.subjectSid&&prep.expectedProofSid===account.proofSid);
  fail("CROSS_ROOT_HOST_PROFILE_MISMATCH",prep.hostProfileId===observerStart.hostProfileId);
  fail("CROSS_ROOT_RELEASE_MISMATCH",observerStart.releaseIdentity&&observerStart.releaseIdentity===read(prep.release?.expectedExtractionRoot??"","release-manifest.json").version);
  const preparationPath=path.join(subjectRoot,"preparation-manifest.json");
  fail("CROSS_ROOT_PREPARATION_DIGEST_MISMATCH",fs.existsSync(preparationPath)&&observerStart.preparationManifestSha256===sha256File(preparationPath));
  fail("CROSS_ROOT_GOVERNANCE_DIGEST_MISMATCH",observerStart.governanceDecisionSha256===prep.governanceDecisionDigest);
  fail("CROSS_ROOT_RELEASE_ZIP_MISMATCH",observerStart.releaseZipSha256===prep.release?.zipSha256);
  fail("CROSS_ROOT_EXTRACTED_TREE_MISMATCH",observerStart.extractedTreeSha256===prep.release?.extractedTreeDigest);
  fail("CROSS_ROOT_RELEASE_MANIFEST_MISMATCH",observerStart.releaseManifestSha256===prep.release?.releaseManifestDigest);
  fail("OBSERVER_EVIDENCE_BEFORE_PREPARATION",Date.parse(observerStart.launchTimestamp)>=Date.parse(prep.preparedAt));
  fail("OBSERVER_EVIDENCE_REPLAYED",Number.isInteger(observerStart.pid)&&observerStart.pid>0&&observerStart.sessionId===prep.sessionId);
  fail("OBSERVER_READY_ORDER_INVALID",Date.parse(observerStart.observerReadyAt)<Date.parse(workflowStart.workflowStartedAt));
  fail("OBSERVER_COMPLETION_ORDER_INVALID",Date.parse(observerComplete.monitorStoppedAt)>Date.parse(workflowComplete.workflowCompletedAt));
  fail("SUBJECT_ADMINISTRATOR_MEMBERSHIP",!(account.localGroupSids??[]).includes("S-1-5-32-544")&&!(account.tokenGroupSids??account.enabledGroupSids??[]).includes("S-1-5-32-544"));
  fail("SUBJECT_PERFORMANCE_LOG_USERS_MEMBERSHIP",!(account.localGroupSids??[]).includes("S-1-5-32-559")&&!(account.tokenGroupSids??[]).includes("S-1-5-32-559"));
  fail("SUBJECT_GROUP_EVIDENCE_INCOMPLETE",Array.isArray(account.localGroupSids)&&Array.isArray(account.tokenGroupSids)&&Array.isArray(account.tokenGroupObservations)&&account.tokenGroupObservations.every((g:any)=>/^S-1-5-/.test(g.sid)&&g.resolved===true));
  fail("SUBJECT_GROUP_EVIDENCE_CONFLICT",["S-1-5-32-544","S-1-5-32-559"].every(sid=>(account.localGroupSids??[]).includes(sid)===(account.tokenGroupSids??[]).includes(sid)));
  const provenance=read(subjectRoot,"pre/collector-provenance.json"),release=read(subjectRoot,"pre/release-runtime.json"),desktop=read(subjectRoot,"pre/desktop.json"),eventFile=path.join(observerRoot,"monitor-events.ndjson"),events=fs.existsSync(eventFile)?fs.readFileSync(eventFile,"utf8").split(/\r?\n/).filter(Boolean).map(line=>{const e=JSON.parse(line);return{...e,timestamp:e.eventTimestamp,executableName:e.processName,executablePath:e.enrichment?.executablePath,ownerSid:e.enrichment?.ownerSid,sessionId:e.enrichment?.sessionId}}):[],tree=deriveSubjectProcessTree(events,{collectorPid:provenance.collectorPid,runtimePid:release.pid,desktopPid:desktop.rootPid,subjectSid:account.proofSid,windowsSessionId:account.windowsSessionId},{startedAt:workflowStart.workflowStartedAt,completedAt:workflowComplete.workflowCompletedAt});
  fail("SUBJECT_PROCESS_TREE_UNDERIVED",tree.some((e:any)=>e.pid===provenance.collectorPid)&&tree.some((e:any)=>e.pid===release.pid)&&tree.some((e:any)=>e.pid===desktop.rootPid));
  fail("PROHIBITED_PROCESS_OBSERVED",!tree.some((e:any)=>/^(git|npm|npx)(\.exe|\.cmd)?$/i.test(e.executableName)||(/^node\.exe$/i.test(e.executableName)&&path.resolve(e.executablePath??"").toLowerCase()!==path.resolve(release.runtimePath??"").toLowerCase())));
  release.runtimePath??=prep.subjectCollector?.runtimePath;
  const releaseManifest=read(prep.release?.expectedExtractionRoot??"","release-manifest.json"),collectorPath=path.join(prep.release?.expectedExtractionRoot??"","collectors","restricted-user-collector.cjs"),collectorEntry=releaseManifest.files?.find((x:any)=>x.path==="collectors/restricted-user-collector.cjs"),binding=auditIdentityBindings({schemaVersion:prep.identityBindingSchema??"",preparation:prep,manifest:read(subjectRoot,EVIDENCE_MANIFEST_FILE),releaseRoot:prep.release?.expectedExtractionRoot??"",repositoryRoot:prep.repository?.canonicalPath??"",releaseManifest,subjectCollector:{relativePath:"collectors/restricted-user-collector.cjs",canonicalPath:collectorPath,size:collectorEntry?.size??0,sha256:fs.existsSync(collectorPath)?sha256File(collectorPath):"",releaseManifestMember:!!collectorEntry,extractedTreeMember:fs.existsSync(collectorPath),runtimePath:release.runtimePath??""},subjectPre:read(subjectRoot,"pre/boot-stage.json"),observerPre:read(observerRoot,"pre-boot-stage.json"),subjectPost:read(subjectRoot,"post/boot-stage.json"),observerPost:read(observerRoot,"post-boot-stage.json"),subsetClaims:[],requestedClaims:[]});
  if(prep.invocationMode==="NON_PROMOTABLE_PRODUCTION_ROUNDTRIP_TEST"){const manifest=read(subjectRoot,EVIDENCE_MANIFEST_FILE),required=["installation/installation-identity.json","pre/subject-collector-identity.json","pre/boot-observation.json","pre/boot-stage.json","observer/pre-boot-observation.json","observer/pre-boot-stage.json","post/subject-collector-identity.json","post/boot-observation.json","post/boot-stage.json","observer/post-boot-observation.json","observer/post-boot-stage.json"],closure=required.every(p=>manifest.files?.some((e:any)=>e.path===p))&&(manifest.files??[]).every((e:any)=>{const f=path.join(subjectRoot,...String(e.path).split("/"));return fs.existsSync(f)&&fs.statSync(f).size===e.size&&sha256File(f)===e.sha256}),allBindings=binding.installationIdentityVerified&&binding.subjectCollectorVerified&&binding.preRestartBootStageVerified&&binding.postRestartBootStageVerified&&binding.windowsRestartVerified,roundTripReasons=[...binding.reasonCodes,...(!closure?["IDENTITY_MANIFEST_CLOSURE_REQUIRED"]:[])];return{...binding,ok:false,status:"BLOCKED",profileId:RESTRICTED_USER_PROFILE_ID,reasonCodes:allBindings&&closure?["NON_PROMOTABLE_PRODUCTION_ROUNDTRIP"]:[...new Set(roundTripReasons)].sort(),grantedClaims:[],claimsGranted:[],deniedClaims:["CROSS_HOST_PORTABILITY_PROVEN"],manifestDigest:manifest.manifestDigest} as any}
  for(const code of binding.reasonCodes)fail(code,false);const ok=subjectResult.ok&&observerResult.observerEvidenceVerified===true&&binding.installationIdentityVerified&&binding.subjectCollectorVerified&&binding.preRestartBootStageVerified&&binding.postRestartBootStageVerified&&binding.windowsRestartVerified&&reasons.length===0;
  return{...binding,ok,status:ok?"RESTRICTED_PROOF_VERIFIED":"BLOCKED",profileId:RESTRICTED_USER_PROFILE_ID,reasonCodes:[...new Set(reasons)].sort(),grantedClaims:ok?["RELEASE_INDEPENDENCE_PROVEN","CERTIFIED_HOST_PROFILE_PROVEN"]:[],deniedClaims:["CROSS_HOST_PORTABILITY_PROVEN"],manifestDigest:subjectResult.manifestDigest};
}

export const proveIntegratedRestrictedUserEvidence=(subjectRoot?:string,observerRoot?:string)=>verifyIntegratedRestrictedUserEvidence(subjectRoot,observerRoot);
export function restrictedUserRestoreNetworkPlan(root: string): Record<string, unknown> { const result = verifyRestrictedUserEvidence(root); return { ok: false, status: "OPERATOR_APPROVAL_REQUIRED", executesSystemChanges: false, verifiedEvidence: result.ok, evidenceManifestDigest: result.manifestDigest, reasonCodes: result.ok ? ["EXPLICIT_OPERATOR_APPROVAL_REQUIRED"] : result.reasonCodes }; }
export function restrictedUserCleanupPlan(root?: string): Record<string, unknown> { if (!root) return { ok: false, status: "BLOCKED", executesSystemChanges: false, reasonCodes: ["VERIFIED_EVIDENCE_ROOT_REQUIRED"] }; const result = verifyRestrictedUserEvidence(root); return { ok: false, status: result.ok ? "OPERATOR_APPROVAL_REQUIRED" : "BLOCKED", executesSystemChanges: false, evidenceRoot: path.resolve(root), evidenceManifestDigest: result.manifestDigest, reasonCodes: result.ok ? ["EXPLICIT_OPERATOR_APPROVAL_REQUIRED"] : result.reasonCodes }; }
function blocked(reasonCodes: string[]): RestrictedUserVerification { return { ok: false, status: "BLOCKED", profileId: RESTRICTED_USER_PROFILE_ID, reasonCodes, grantedClaims: [], deniedClaims: ["CROSS_HOST_PORTABILITY_PROVEN"] }; }
