import os from "node:os";
import { sha256 } from "./restricted-user-evidence";
import { minimalWindowsEnvironment, runWindowsCommand, WINDOWS_TOOLS, type CommandObservation } from "./restricted-user-command-runner";

export function parseWhoamiCsv(text: string): string[][] { return text.split(/\r?\n/).filter(Boolean).map((line) => [...line.matchAll(/"((?:[^"]|"")*)"(?:,|$)/g)].map((m) => m[1].replace(/""/g, '"'))); }
export function parseWhoamiUser(text: string): { username: string; sid: string } { const row = parseWhoamiCsv(text)[0] ?? []; if (row.length < 2 || !/^S-1-/.test(row[1])) throw new Error("WHOAMI_USER_INVALID"); return { username: row[0], sid: row[1] }; }
export function parseWhoamiGroups(text: string): Array<{ name: string; sid: string; attributes: string[]; enabled: boolean }> { return parseWhoamiCsv(text).map((r) => ({ name: r[0], sid: r[1], attributes: String(r[3] ?? "").split(",").map((x) => x.trim()).filter(Boolean), enabled: /enabled/i.test(r[3] ?? "") })); }
export function collectAccountObservation(input: { expectedSid: string; developmentSid: string; expectedAccount: string; run?: typeof runWindowsCommand; profile?: string; profileCreatedAt?: string }): { raw: Record<string, CommandObservation>; normalized: any } {
  const run = input.run ?? runWindowsCommand, user = run(WINDOWS_TOOLS.whoami, ["/user", "/fo", "csv", "/nh"]), groups = run(WINDOWS_TOOLS.whoami, ["/groups", "/fo", "csv", "/nh"]), privileges = run(WINDOWS_TOOLS.whoami, ["/priv", "/fo", "csv", "/nh"]);
  const localScript="$n=[Environment]::GetEnvironmentVariable('SERA_EXPECTED_ACCOUNT');$u=Get-LocalUser -Name $n -ErrorAction Stop;$p=Get-CimInstance Win32_UserProfile|? SID -eq $u.SID.Value|select -First 1;$gs=@(Get-LocalGroup|%{$g=$_;if(Get-LocalGroupMember -Group $g.Name -ErrorAction SilentlyContinue|? SID -eq $u.SID.Value){$g.SID.Value}});[pscustomobject]@{name=$u.Name;sid=$u.SID.Value;enabled=$u.Enabled;principalSource=$u.PrincipalSource.ToString();profilePath=$p.LocalPath;profileLoaded=$p.Loaded;profileLastUse=$p.LastUseTime;localGroupSids=$gs;windowsSessionId=(Get-Process -Id $PID).SessionId}|ConvertTo-Json -Compress",encoded=Buffer.from(localScript,"utf16le").toString("base64"),local=run(WINDOWS_TOOLS.powershell,["-NoProfile","-NonInteractive","-EncodedCommand",encoded],{env:{...minimalWindowsEnvironment(),SERA_EXPECTED_ACCOUNT:input.expectedAccount}});
  if ([user, groups, privileges, local].some((o) => o.failure !== "NONE")) throw new Error("ACCOUNT_OBSERVATION_FAILED");
  const identity = parseWhoamiUser(user.stdout), parsedGroups = parseWhoamiGroups(groups.stdout), adminEnabled = parsedGroups.some((g) => g.sid === "S-1-5-32-544" && g.enabled), elevated = parsedGroups.some((g) => /^S-1-16-(12288|16384)$/.test(g.sid));
  const localAccount=JSON.parse(local.stdout);if (identity.sid !== input.expectedSid) throw new Error("ACTIVE_SID_MISMATCH"); if (identity.sid === input.developmentSid) throw new Error("DEVELOPMENT_SID_USED"); if (adminEnabled || elevated) throw new Error("ELEVATED_TOKEN_REJECTED"); if (!identity.username.toLowerCase().endsWith(`\\${input.expectedAccount.toLowerCase()}`)) throw new Error("ACTIVE_ACCOUNT_MISMATCH");if(localAccount.sid!==identity.sid||localAccount.principalSource!=="Local"||localAccount.enabled!==true)throw new Error("LOCAL_ACCOUNT_IDENTITY_MISMATCH");
  const profilePath = input.profile ?? localAccount.profilePath ?? process.env.USERPROFILE ?? os.homedir();if(pathNormalize(profilePath)!==pathNormalize(process.env.USERPROFILE??profilePath))throw new Error("ACTIVE_PROFILE_MISMATCH");
  return { raw: { user, groups, privileges, local }, normalized: { proofSid: identity.sid, activeTokenSid: identity.sid, username: identity.username, windowsSessionId:localAccount.windowsSessionId, enabledGroupSids: parsedGroups.filter((g) => g.enabled).map((g) => g.sid), tokenGroupSids: parsedGroups.map((g)=>g.sid), tokenGroupObservations:parsedGroups.map(g=>({sid:g.sid,name:g.name,resolved:/^S-1-5-/.test(g.sid),enabled:g.enabled,attributes:g.attributes})), localGroupSids:Array.isArray(localAccount.localGroupSids)?localAccount.localGroupSids:localAccount.localGroupSids?[localAccount.localGroupSids]:[], tokenElevated: false, elevationType: "limited", accountSource: localAccount.principalSource, standardLocalAccount: true, profileSid: localAccount.sid, profilePath, profileCreatedAt: input.profileCreatedAt ?? localAccount.profileLastUse ?? new Date(0).toISOString(), collectorExecutable: WINDOWS_TOOLS.whoami, rawIdentitySha256: sha256(user.stdout), rawGroupsSha256: sha256(groups.stdout), rawTokenSha256: sha256(privileges.stdout), capturedAt: user.completedAt } };
}
function pathNormalize(value:string):string{return value.replace(/[\\/]+$/g,"").toLowerCase();}
